<?php

namespace Database\Seeders;

use App\Models\CertificateTemplate;
use App\Models\Organization;
use App\Services\TemplateLibraryService;
use Illuminate\Database\Seeder;

/**
 * Publishes the original design library (seed assets generated by
 * scripts/generate-template-library.mjs) into the shared certificate_templates
 * store, then provisions sensible default assignments for every organization.
 */
class TemplateLibrarySeeder extends Seeder
{
    public function run(TemplateLibraryService $library): void
    {
        $directory = database_path('seeders/template-library');

        $items = [];
        foreach (glob($directory.'/*/*.json') ?: [] as $file) {
            $decoded = json_decode((string) file_get_contents($file), true);
            if (is_array($decoded)) {
                $items[] = $decoded;
            }
        }

        // The seed directory is the source of truth for the system library.
        // Library rows are upserted by (title, category) so their ids remain
        // stable across reseeds — saved links/assignments keep working. Only
        // rows that no longer exist on disk are purged. Organization copies
        // and slot assignments are untouched (they target copied rows).
        $onDisk = collect($items)
            ->map(fn ($item) => ($item['category'] ?? 'general').'|'.($item['title'] ?? ''))
            ->values();

        CertificateTemplate::query()
            ->whereNull('organization_id')
            ->get()
            ->each(function ($row) use ($onDisk) {
                if (!$onDisk->contains($row->category.'|'.$row->title)) {
                    $row->delete();
                }
            });

        $written = $library->publish($items);

        foreach (Organization::query()->get() as $organization) {
            $library->provisionDefaults($organization);
        }

        $this->command?->info("[TemplateLibrarySeeder] published {$written} library templates and provisioned default slot assignments.");
    }
}