<?php

use App\Http\Controllers\AdmissionInquiryController;
use App\Http\Controllers\AiAssistantController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BankAccountController;
use App\Http\Controllers\AutoTimetableController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\BiometricSettingsController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\ClassesController;
use App\Http\Controllers\CommunicationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EbookLibraryController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\HelpdeskController;
use App\Http\Controllers\OnlineClassController;
use App\Http\Controllers\OnlinePaymentController;
use App\Http\Controllers\PtmController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\QrAttendanceController;
use App\Http\Controllers\QuestionBankController;
use App\Http\Controllers\RecruitmentController;
use App\Http\Controllers\ReportCardController;
use App\Http\Controllers\ScholarshipController;
use App\Http\Controllers\StaffIdCardController;
use App\Http\Controllers\StudyMaterialController;
use App\Http\Controllers\SyllabusUnitController;
use App\Http\Controllers\TallyExportController;
use App\Http\Controllers\TeacherEvaluationController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FeesController;
use App\Http\Controllers\FrontOfficeController;
use App\Http\Controllers\HealthRecordsController;
use App\Http\Controllers\HomeworkController;
use App\Http\Controllers\HostelManagementController;
use App\Http\Controllers\IncidentsController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\OnlineExamController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\LanguageTranslationController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\PromoteStudentsController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SsoController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\SubjectsController;
use App\Http\Controllers\TodoController;
use App\Http\Controllers\TransportManagementController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\WebsitePageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return app(SettingsController::class)->publicHome();
});
Route::get('/privacy-policy', [SettingsController::class, 'publicPrivacyPolicy'])->name('privacy-policy');
Route::get('/admissions/apply', [SettingsController::class, 'publicAdmissionForm'])->name('admissions.apply');
Route::get('/pages/{slug}', [WebsitePageController::class, 'show'])->name('website-pages.show');
Route::get('/login', [LoginController::class, 'viewLogin'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('/sso/status', [SsoController::class, 'status'])->name('sso.status');
if (filter_var(env('SSO_ENABLED', false), FILTER_VALIDATE_BOOL)) {
    Route::get('/auth/sso/{provider}', [SsoController::class, 'redirect'])->name('sso.redirect');
    Route::get('/auth/sso/{provider}/callback', [SsoController::class, 'callback'])->name('sso.callback');
}
Route::middleware('guest')->group(function () {
    Route::get('/forgot-password', [PasswordResetController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'store'])->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'edit'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'update'])->name('password.update');
});
Route::post('/admissions/send-verification-code', [AdmissionInquiryController::class, 'sendVerificationCode'])->name('admissions.send-verification-code');
Route::post('/admissions/verify-code', [AdmissionInquiryController::class, 'verifyCode'])->name('admissions.verify-code');
Route::post('/admissions', [AdmissionInquiryController::class, 'store'])->name('admissions.store');
Route::get('/admissions/verify/{token}', [AdmissionInquiryController::class, 'verify'])
    ->middleware('signed')
    ->name('admissions.verify');
Route::middleware(['auth', 'organization.subscription'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('staff.permission:Dashboard Home,view')->name('dashboard');
    Route::post('/superadmin/organizations', [DashboardController::class, 'storeOrganization'])->name('superadmin.organizations.store');
    Route::patch('/superadmin/organizations/{organization}', [DashboardController::class, 'updateOrganization'])->name('superadmin.organizations.update');
    Route::delete('/superadmin/organizations/{organization}', [DashboardController::class, 'destroyOrganization'])->name('superadmin.organizations.destroy');
    Route::post('/superadmin/organizations/{organization}/impersonate', [DashboardController::class, 'impersonateOrganizationAdmin'])->name('superadmin.organizations.impersonate');
    Route::post('/superadmin/impersonation/leave', [DashboardController::class, 'leaveImpersonation'])->name('superadmin.impersonation.leave');
    Route::get('/superadmin/organizations', [DashboardController::class, 'organizations'])->name('superadmin.organizations');
    Route::get('/superadmin/smtp-settings', [DashboardController::class, 'smtpSettings'])->name('superadmin.smtp-settings');
    Route::patch('/superadmin/smtp-settings', [DashboardController::class, 'updateSmtpSettings'])->name('superadmin.smtp-settings.update');
    Route::post('/superadmin/smtp-settings/test', [DashboardController::class, 'sendTestSmtpMail'])->name('superadmin.smtp-settings.test');
    Route::get('/superadmin/knowledge-base-cms', [DashboardController::class, 'knowledgeBaseCms'])->name('superadmin.knowledge-base-cms');
    Route::patch('/superadmin/knowledge-base-cms', [DashboardController::class, 'updateKnowledgeBaseCms'])->name('superadmin.knowledge-base-cms.update');
    Route::get('/superadmin/profile', [DashboardController::class, 'profile'])->name('superadmin.profile');
    Route::get('/superadmin/profile/edit', [DashboardController::class, 'editProfile'])->name('superadmin.profile.edit');
    Route::get('/students', [StudentsController::class, 'index'])->middleware('staff.permission:Search Students,view')->name('students');
    Route::post('/students', [StudentsController::class, 'store'])->middleware('staff.permission:Search Students,add')->name('students.store');
    Route::post('/students/import', [StudentsController::class, 'import'])->middleware('staff.permission:Search Students,add')->name('students.import');
    Route::delete('/students/imports/{studentImport}', [StudentsController::class, 'destroyImport'])->middleware('staff.permission:Search Students,delete')->name('students.imports.destroy');
    Route::post('/students/bulk-delete', [StudentsController::class, 'bulkDestroy'])->middleware('staff.permission:Bulk Delete Students,delete')->name('students.bulk-destroy');
    Route::get('/students/create', [StudentsController::class, 'create'])->middleware('staff.permission:Search Students,add')->name('students.create');
    Route::patch('/students/{student}', [StudentsController::class, 'update'])->middleware('staff.permission:Edit Student,edit')->name('students.update');
    Route::delete('/students/{student}', [StudentsController::class, 'destroy'])->middleware('staff.permission:Bulk Delete Students,delete')->name('students.destroy');
    Route::get('/students/{student}', [StudentsController::class, 'show'])->middleware('staff.permission:Student Details,view')->name('students.show');
    Route::get('/students/{student}/edit', [StudentsController::class, 'edit'])->middleware('staff.permission:Edit Student,view')->name('students.edit');
    Route::get('/search_students', [StudentsController::class, 'index'])->middleware('staff.permission:Search Students,view')->name('search_students');
    Route::get('/bulk-delete-students', [StudentsController::class, 'bulkDelete'])->middleware('staff.permission:Bulk Delete Students,view')->name('bulk-delete-students');
    Route::get('/alumni-records', [StudentsController::class, 'alumniRecords'])->middleware('staff.permission:Alumni Records,view')->name('alumni-records');
    Route::get('/online-admission', [AdmissionInquiryController::class, 'index'])->middleware('staff.permission:Online Admission,view')->name('online-admission');
    Route::post('/online-admission/{admissionInquiry}/enroll', [AdmissionInquiryController::class, 'enroll'])->middleware('staff.permission:Online Admission,add')->name('online-admission.enroll');
    Route::patch('/online-admission/{admissionInquiry}', [AdmissionInquiryController::class, 'update'])->middleware('staff.permission:Online Admission,edit')->name('online-admission.update');
    Route::delete('/online-admission/{admissionInquiry}', [AdmissionInquiryController::class, 'destroy'])->middleware('staff.permission:Online Admission,delete')->name('online-admission.destroy');
    Route::get('/staff', [UsersController::class, 'index'])->middleware('staff.permission:User Management,view')->name('users');
    Route::get('/staff/daily-attendance', [UsersController::class, 'dailyAttendance'])->middleware('staff.permission:Staff Attendance,view')->name('staff.daily-attendance');
    Route::post('/staff/daily-attendance', [UsersController::class, 'storeDailyAttendance'])->middleware('staff.permission:Staff Attendance,edit')->name('staff.daily-attendance.store');
    Route::get('/staff/payroll-management', [UsersController::class, 'payrollManagement'])->middleware('staff.permission:Payroll Management,view')->name('staff.payroll-management');
    Route::post('/staff/payroll-management', [UsersController::class, 'storePayroll'])->middleware('staff.permission:Payroll Management,edit')->name('staff.payroll-management.store');
    Route::get('/staff/payroll-management/{payrollEntry}/payslip', [UsersController::class, 'printPayslip'])->middleware('staff.permission:Payroll Management,view')->name('staff.payroll-management.payslip');
    Route::get('/staff/payroll-management/{payrollEntry}/payslip/download', [UsersController::class, 'downloadPayslip'])->middleware('staff.permission:Payroll Management,view')->name('staff.payroll-management.payslip.download');
    Route::get('/staff/leave-management', [UsersController::class, 'leaveManagement'])->middleware('staff.permission:Leave Management,view')->name('staff.leave-management');
    Route::post('/staff/leave-management', [UsersController::class, 'storeLeaveRequest'])->middleware('staff.permission:Leave Management,add')->name('staff.leave-management.store');
    Route::patch('/staff/leave-management/{leaveRequest}', [UsersController::class, 'updateLeaveRequest'])->middleware('staff.permission:Leave Management,edit')->name('staff.leave-management.update');
    Route::patch('/staff/leave-management/{leaveRequest}/status', [UsersController::class, 'updateLeaveRequestStatus'])->middleware('staff.permission:Leave Management,edit')->name('staff.leave-management.status');
    Route::delete('/staff/leave-management/{leaveRequest}', [UsersController::class, 'destroyLeaveRequest'])->middleware('staff.permission:Leave Management,delete')->name('staff.leave-management.destroy');
    Route::post('/staff/leave-management/balances', [UsersController::class, 'updateLeaveBalances'])->middleware('staff.permission:Leave Management,edit')->name('staff.leave-management.balances');
    Route::get('/my-leaves', [ProfileController::class, 'leaves'])->middleware('staff.permission:My Leaves,view')->name('my-leaves');
    Route::post('/my-leaves', [ProfileController::class, 'storeLeave'])->middleware('staff.permission:My Leaves,add')->name('my-leaves.store');
    Route::post('/staff', [UsersController::class, 'store'])->middleware('staff.permission:User Management,add')->name('users.store');
    Route::patch('/staff/{managedUser}', [UsersController::class, 'update'])->middleware('staff.permission:User Management,edit')->name('users.update');
    Route::patch('/staff/{managedUser}/status', [UsersController::class, 'updateStatus'])->middleware('staff.permission:User Management,edit')->name('users.status');
    Route::post('/staff/{managedUser}/reset-password', [UsersController::class, 'resetPassword'])->middleware('staff.permission:User Management,edit')->name('users.reset-password');
    Route::delete('/staff/{managedUser}', [UsersController::class, 'destroy'])->middleware('staff.permission:User Management,delete')->name('users.destroy');
    Route::post('/staff/designations', [UsersController::class, 'storeDesignation'])->middleware('staff.permission:User Management,add')->name('users.designations.store');
    Route::delete('/staff/designations/{designation}', [UsersController::class, 'destroyDesignation'])->middleware('staff.permission:User Management,delete')->name('users.designations.destroy');
    Route::post('/staff/departments', [UsersController::class, 'storeDepartment'])->middleware('staff.permission:User Management,add')->name('users.departments.store');
    Route::delete('/staff/departments/{department}', [UsersController::class, 'destroyDepartment'])->middleware('staff.permission:User Management,delete')->name('users.departments.destroy');
    Route::get('/classes', [ClassesController::class, 'index'])->middleware('staff.permission:Class / Section,view')->name('classes');
    Route::post('/classes', [ClassesController::class, 'store'])->middleware('staff.permission:Class / Section,add')->name('classes.store');
    Route::patch('/classes/{schoolClass}', [ClassesController::class, 'update'])->middleware('staff.permission:Class / Section,edit')->name('classes.update');
    Route::delete('/classes/{schoolClass}', [ClassesController::class, 'destroy'])->middleware('staff.permission:Class / Section,delete')->name('classes.destroy');
    Route::post('/classes/sections', [ClassesController::class, 'storeSection'])->middleware('staff.permission:Class / Section,add')->name('classes.sections.store');
    Route::patch('/classes/sections/{section}', [ClassesController::class, 'updateSection'])->middleware('staff.permission:Class / Section,edit')->name('classes.sections.update');
    Route::delete('/classes/sections/{section}', [ClassesController::class, 'destroySection'])->middleware('staff.permission:Class / Section,delete')->name('classes.sections.destroy');
    Route::get('/class-time-table', [ClassesController::class, 'classTimeTable'])->middleware('staff.permission:Class Time Table,view')->name('class-time-table');
    Route::post('/class-time-table', [ClassesController::class, 'storeTimeTableEntry'])->middleware('staff.permission:Class Time Table,add')->name('class-time-table.store');
    Route::patch('/class-time-table/{timetable}', [ClassesController::class, 'updateTimeTableEntry'])->middleware('staff.permission:Class Time Table,edit')->name('class-time-table.update');
    Route::delete('/class-time-table/{timetable}', [ClassesController::class, 'destroyTimeTableEntry'])->middleware('staff.permission:Class Time Table,delete')->name('class-time-table.destroy');
    Route::get('/teacher-time-table', [ClassesController::class, 'teacherTimeTable'])->middleware('staff.permission:Teachers Time Table,view')->name('teacher-time-table');
    Route::get('/lesson-plan', [ClassesController::class, 'lessonPlan'])->middleware('staff.permission:Lesson Plan,view')->name('lesson-plan');
    Route::post('/lesson-plan', [ClassesController::class, 'storeLessonPlan'])->middleware('staff.permission:Lesson Plan,add')->name('lesson-plan.store');
    Route::patch('/lesson-plan/{lessonPlan}', [ClassesController::class, 'updateLessonPlan'])->middleware('staff.permission:Lesson Plan,edit')->name('lesson-plan.update');
    Route::delete('/lesson-plan/{lessonPlan}', [ClassesController::class, 'destroyLessonPlan'])->middleware('staff.permission:Lesson Plan,edit')->name('lesson-plan.destroy');
    Route::get('/homework', [HomeworkController::class, 'index'])->middleware('staff.permission:Homework,view')->name('homework');
    Route::post('/homework', [HomeworkController::class, 'store'])->middleware('staff.permission:Homework,add')->name('homework.store');
    Route::delete('/homework/{homework}', [HomeworkController::class, 'destroy'])->middleware('staff.permission:Homework,delete')->name('homework.destroy');
    Route::post('/homework/{homework}/submit', [HomeworkController::class, 'submit'])->name('homework.submit');
    Route::patch('/homework-submissions/{homeworkSubmission}/evaluate', [HomeworkController::class, 'evaluate'])->middleware('staff.permission:Homework,edit')->name('homework-submissions.evaluate');
    Route::get('/homework/{homework}/attachments/{index}', [HomeworkController::class, 'downloadAttachment'])->name('homework.attachment.download');
    Route::get('/homework/{homework}/attachments/{index}/preview', [HomeworkController::class, 'previewAttachment'])->name('homework.attachment.preview');
    Route::get('/homework-submissions/{homeworkSubmission}/attachments/{index}', [HomeworkController::class, 'downloadSubmissionAttachment'])->name('homework.submission.attachment.download');
    Route::get('/homework-submissions/{homeworkSubmission}/attachments/{index}/preview', [HomeworkController::class, 'previewSubmissionAttachment'])->name('homework.submission.attachment.preview');
    Route::get('/subjects', [SubjectsController::class, 'index'])->middleware('staff.permission:Subjects,view')->name('subjects');
    Route::post('/subjects', [SubjectsController::class, 'store'])->middleware('staff.permission:Subjects,add')->name('subjects.store');
    Route::patch('/subjects/{subject}', [SubjectsController::class, 'update'])->middleware('staff.permission:Subjects,edit')->name('subjects.update');
    Route::delete('/subjects/{subject}', [SubjectsController::class, 'destroy'])->middleware('staff.permission:Subjects,delete')->name('subjects.destroy');
    Route::get('/promote-students', [PromoteStudentsController::class, 'index'])->middleware('staff.permission:Promote Students,view')->name('promote-students');
    Route::post('/promote-students/promote', [PromoteStudentsController::class, 'promote'])->middleware('staff.permission:Promote Students,add')->name('promote-students.promote');
    Route::post('/promote-students/alumni', [PromoteStudentsController::class, 'saveToAlumni'])->middleware('staff.permission:Promote Students,add')->name('promote-students.alumni');
    Route::get('/admission-enquiry', [FrontOfficeController::class, 'admissionEnquiry'])->middleware('staff.permission:Admission Enquiry,view')->name('admission-enquiry');
    Route::post('/admission-enquiry', [FrontOfficeController::class, 'storeAdmissionEnquiry'])->middleware('staff.permission:Admission Enquiry,add')->name('admission-enquiry.store');
    Route::patch('/admission-enquiry/{admissionInquiry}', [FrontOfficeController::class, 'updateAdmissionEnquiry'])->middleware('staff.permission:Admission Enquiry,edit')->name('admission-enquiry.update');
    Route::delete('/admission-enquiry/{admissionInquiry}', [FrontOfficeController::class, 'destroyAdmissionEnquiry'])->middleware('staff.permission:Admission Enquiry,delete')->name('admission-enquiry.destroy');
    Route::get('/leads', [LeadController::class, 'index'])->middleware('staff.permission:Admission Leads,view')->name('leads.index');
    Route::post('/leads', [LeadController::class, 'store'])->middleware('staff.permission:Admission Leads,add')->name('leads.store');
    Route::patch('/leads/{lead}', [LeadController::class, 'update'])->middleware('staff.permission:Admission Leads,edit')->name('leads.update');
    Route::delete('/leads/{lead}', [LeadController::class, 'destroy'])->middleware('staff.permission:Admission Leads,delete')->name('leads.destroy');
    Route::get('/visitor-register', [FrontOfficeController::class, 'visitorRegister'])->middleware('staff.permission:Visitor Register,view')->name('visitor-register');
    Route::post('/visitor-register', [FrontOfficeController::class, 'storeVisitorRegister'])->middleware('staff.permission:Visitor Register,add')->name('visitor-register.store');
    Route::patch('/visitor-register/{visitorRegisterEntry}', [FrontOfficeController::class, 'updateVisitorRegister'])->middleware('staff.permission:Visitor Register,edit')->name('visitor-register.update');
    Route::delete('/visitor-register/{visitorRegisterEntry}', [FrontOfficeController::class, 'destroyVisitorRegister'])->middleware('staff.permission:Visitor Register,delete')->name('visitor-register.destroy');
    Route::get('/phone-call-log', [FrontOfficeController::class, 'phoneCallLog'])->middleware('staff.permission:Phone Call Log,view')->name('phone-call-log');
    Route::post('/phone-call-log', [FrontOfficeController::class, 'storePhoneCallLog'])->middleware('staff.permission:Phone Call Log,add')->name('phone-call-log.store');
    Route::patch('/phone-call-log/{phoneCallLogEntry}', [FrontOfficeController::class, 'updatePhoneCallLog'])->middleware('staff.permission:Phone Call Log,edit')->name('phone-call-log.update');
    Route::delete('/phone-call-log/{phoneCallLogEntry}', [FrontOfficeController::class, 'destroyPhoneCallLog'])->middleware('staff.permission:Phone Call Log,delete')->name('phone-call-log.destroy');
    Route::get('/postal-dispatch', [FrontOfficeController::class, 'postalDispatch'])->middleware('staff.permission:Postal Dispatch,view')->name('postal-dispatch');
    Route::post('/postal-dispatch', [FrontOfficeController::class, 'storePostalDispatch'])->middleware('staff.permission:Postal Dispatch,add')->name('postal-dispatch.store');
    Route::patch('/postal-dispatch/{postalDispatchEntry}', [FrontOfficeController::class, 'updatePostalDispatch'])->middleware('staff.permission:Postal Dispatch,edit')->name('postal-dispatch.update');
    Route::delete('/postal-dispatch/{postalDispatchEntry}', [FrontOfficeController::class, 'destroyPostalDispatch'])->middleware('staff.permission:Postal Dispatch,delete')->name('postal-dispatch.destroy');
    Route::get('/postal-delivery', [FrontOfficeController::class, 'postalDelivery'])->middleware('staff.permission:Postal Delivery,view')->name('postal-delivery');
    Route::post('/postal-delivery', [FrontOfficeController::class, 'storePostalDelivery'])->middleware('staff.permission:Postal Delivery,add')->name('postal-delivery.store');
    Route::patch('/postal-delivery/{postalDeliveryEntry}', [FrontOfficeController::class, 'updatePostalDelivery'])->middleware('staff.permission:Postal Delivery,edit')->name('postal-delivery.update');
    Route::delete('/postal-delivery/{postalDeliveryEntry}', [FrontOfficeController::class, 'destroyPostalDelivery'])->middleware('staff.permission:Postal Delivery,delete')->name('postal-delivery.destroy');
    Route::get('/complains', [FrontOfficeController::class, 'complains'])->middleware('staff.permission:Complains,view')->name('complains');
    Route::post('/complains', [FrontOfficeController::class, 'storeComplaint'])->middleware('staff.permission:Complains,add')->name('complains.store');
    Route::patch('/complains/{complaintEntry}', [FrontOfficeController::class, 'updateComplaint'])->middleware('staff.permission:Complains,edit')->name('complains.update');
    Route::delete('/complains/{complaintEntry}', [FrontOfficeController::class, 'destroyComplaint'])->middleware('staff.permission:Complains,delete')->name('complains.destroy');
    Route::get('/fees', [FeesController::class, 'index'])->middleware('staff.permission:Fees Management,view')->name('fees');
    Route::post('/fees/types', [FeesController::class, 'storeFeeType'])->middleware('staff.permission:Fees Management,add')->name('fees.types.store');
    Route::patch('/fees/types/{feeType}', [FeesController::class, 'updateFeeType'])->middleware('staff.permission:Fees Management,edit')->name('fees.types.update');
    Route::delete('/fees/types/{feeType}', [FeesController::class, 'destroyFeeType'])->middleware('staff.permission:Fees Management,delete')->name('fees.types.destroy');
    Route::post('/fees/structures', [FeesController::class, 'storeStructure'])->middleware('staff.permission:Fees Management,add')->name('fees.structures.store');
    Route::patch('/fees/structures/{feeStructure}', [FeesController::class, 'updateStructure'])->middleware('staff.permission:Fees Management,edit')->name('fees.structures.update');
    Route::delete('/fees/structures/{feeStructure}', [FeesController::class, 'destroyStructure'])->middleware('staff.permission:Fees Management,delete')->name('fees.structures.destroy');
    Route::post('/fees/assign', [FeesController::class, 'assignFees'])->middleware('staff.permission:Fees Management,add')->name('fees.assign');
    Route::post('/fees/import', [FeesController::class, 'importFees'])->middleware('staff.permission:Fees Management,add')->name('fees.import');
    Route::post('/fees/carry-forward', [FeesController::class, 'carryForward'])->middleware('staff.permission:Fees Management,add')->name('fees.carry-forward');
    Route::post('/fees/payments', [FeesController::class, 'collectPayment'])->middleware('staff.permission:Fees Management,add')->name('fees.payments.store');
    Route::post('/fees/payments/{feePayment}/revert', [FeesController::class, 'revertPayment'])->middleware('staff.permission:Fees Management,edit')->name('fees.payments.revert');
    Route::post('/fees/payments/{feePayment}/approve', [OnlinePaymentController::class, 'approvePending'])->middleware('staff.permission:Fees Management,edit')->name('fees.payments.approve');
    Route::post('/fees/online/pay', [OnlinePaymentController::class, 'pay'])->middleware('staff.permission:Fees Management,view')->name('fees.online.pay');
    Route::post('/fees/online/razorpay/verify', [OnlinePaymentController::class, 'razorpayVerify'])->middleware('staff.permission:Fees Management,view')->name('fees.online.razorpay.verify');
    Route::post('/fees/online/upi/confirm', [OnlinePaymentController::class, 'upiConfirm'])->middleware('staff.permission:Fees Management,view')->name('fees.online.upi.confirm');
    Route::get('/fees/challans', [FeesController::class, 'challans'])->middleware('staff.permission:Fees Management,view')->name('fees.challans');
    Route::get('/fees/challans/{studentFee}/print', [FeesController::class, 'printChallan'])->middleware('staff.permission:Fees Management,view')->name('fees.challans.print');
    Route::get('/fees/challans/{studentFee}/download', [FeesController::class, 'downloadChallan'])->middleware('staff.permission:Fees Management,view')->name('fees.challans.download');
    Route::get('/fees/due-slips', [FeesController::class, 'dueSlips'])->middleware('staff.permission:Fees Management,view')->name('fees.due-slips');
    Route::get('/fees/due-slips/{student}/print', [FeesController::class, 'printDueSlip'])->middleware('staff.permission:Fees Management,view')->name('fees.due-slips.print');
    Route::get('/fees/due-slips/{student}/download', [FeesController::class, 'downloadDueSlip'])->middleware('staff.permission:Fees Management,view')->name('fees.due-slips.download');
    Route::get('/fees/audit', [FeesController::class, 'feeAudit'])->middleware('staff.permission:Fees Management,view')->name('fees.audit');
    Route::get('/income-management', [FeesController::class, 'income'])->middleware('staff.permission:Income Management,view')->name('income-management');
    Route::post('/income-management', [FeesController::class, 'storeIncome'])->middleware('staff.permission:Income Management,add')->name('income-management.store');
    Route::post('/income-management/import', [FeesController::class, 'importIncome'])->middleware('staff.permission:Income Management,add')->name('income-management.import');
    Route::patch('/income-management/{incomeEntry}', [FeesController::class, 'updateIncome'])->middleware('staff.permission:Income Management,edit')->name('income-management.update');
    Route::delete('/income-management/{incomeEntry}', [FeesController::class, 'destroyIncome'])->middleware('staff.permission:Income Management,delete')->name('income-management.destroy');
    Route::get('/expense-management', [FeesController::class, 'expenses'])->middleware('staff.permission:Expense Management,view')->name('expense-management');
    Route::post('/expense-management', [FeesController::class, 'storeExpense'])->middleware('staff.permission:Expense Management,add')->name('expense-management.store');
    Route::post('/expense-management/import', [FeesController::class, 'importExpense'])->middleware('staff.permission:Expense Management,add')->name('expense-management.import');
    Route::patch('/expense-management/{expenseEntry}', [FeesController::class, 'updateExpense'])->middleware('staff.permission:Expense Management,edit')->name('expense-management.update');
    Route::delete('/expense-management/{expenseEntry}', [FeesController::class, 'destroyExpense'])->middleware('staff.permission:Expense Management,delete')->name('expense-management.destroy');
    Route::get('/bank-accounts', [BankAccountController::class, 'index'])->middleware('staff.permission:Bank Accounts,view')->name('bank-accounts');
    Route::post('/bank-accounts', [BankAccountController::class, 'store'])->middleware('staff.permission:Bank Accounts,add')->name('bank-accounts.store');
    Route::patch('/bank-accounts/{bankAccount}', [BankAccountController::class, 'update'])->middleware('staff.permission:Bank Accounts,edit')->name('bank-accounts.update');
    Route::delete('/bank-accounts/{bankAccount}', [BankAccountController::class, 'destroy'])->middleware('staff.permission:Bank Accounts,delete')->name('bank-accounts.destroy');
    Route::post('/bank-accounts/{bankAccount}/set-default', [BankAccountController::class, 'setDefault'])->middleware('staff.permission:Bank Accounts,edit')->name('bank-accounts.set-default');
    Route::post('/bank-accounts/transactions', [BankAccountController::class, 'storeTransaction'])->middleware('staff.permission:Bank Accounts,add')->name('bank-accounts.transactions.store');
    Route::get('/hostel-management', [HostelManagementController::class, 'index'])->middleware('staff.permission:Hostel Management,view')->name('hostel-management');
    Route::post('/hostel-management/hostels', [HostelManagementController::class, 'storeHostel'])->middleware('staff.permission:Hostel Management,add')->name('hostel-management.hostels.store');
    Route::patch('/hostel-management/hostels/{hostel}', [HostelManagementController::class, 'updateHostel'])->middleware('staff.permission:Hostel Management,edit')->name('hostel-management.hostels.update');
    Route::delete('/hostel-management/hostels/{hostel}', [HostelManagementController::class, 'destroyHostel'])->middleware('staff.permission:Hostel Management,delete')->name('hostel-management.hostels.destroy');
    Route::post('/hostel-management/rooms', [HostelManagementController::class, 'storeRoom'])->middleware('staff.permission:Hostel Management,add')->name('hostel-management.rooms.store');
    Route::patch('/hostel-management/rooms/{hostelRoom}', [HostelManagementController::class, 'updateRoom'])->middleware('staff.permission:Hostel Management,edit')->name('hostel-management.rooms.update');
    Route::delete('/hostel-management/rooms/{hostelRoom}', [HostelManagementController::class, 'destroyRoom'])->middleware('staff.permission:Hostel Management,delete')->name('hostel-management.rooms.destroy');
    Route::post('/hostel-management/beds', [HostelManagementController::class, 'storeBed'])->middleware('staff.permission:Hostel Management,add')->name('hostel-management.beds.store');
    Route::patch('/hostel-management/beds/{hostelBed}', [HostelManagementController::class, 'updateBed'])->middleware('staff.permission:Hostel Management,edit')->name('hostel-management.beds.update');
    Route::delete('/hostel-management/beds/{hostelBed}', [HostelManagementController::class, 'destroyBed'])->middleware('staff.permission:Hostel Management,delete')->name('hostel-management.beds.destroy');
    Route::post('/hostel-management/fee-structures', [HostelManagementController::class, 'storeFeeStructure'])->middleware('staff.permission:Hostel Management,add')->name('hostel-management.fee-structures.store');
    Route::patch('/hostel-management/fee-structures/{hostelFeeStructure}', [HostelManagementController::class, 'updateFeeStructure'])->middleware('staff.permission:Hostel Management,edit')->name('hostel-management.fee-structures.update');
    Route::delete('/hostel-management/fee-structures/{hostelFeeStructure}', [HostelManagementController::class, 'destroyFeeStructure'])->middleware('staff.permission:Hostel Management,delete')->name('hostel-management.fee-structures.destroy');
    Route::post('/hostel-management/complaints', [HostelManagementController::class, 'storeComplaint'])->middleware('staff.permission:Hostel Complaints,add')->name('hostel-management.complaints.store');
    Route::patch('/hostel-management/complaints/{complaintEntry}/status', [HostelManagementController::class, 'updateComplaintStatus'])->middleware('staff.permission:Hostel Complaints,edit')->name('hostel-management.complaints.status');
    Route::post('/hostel-management/notices', [HostelManagementController::class, 'storeNotice'])->middleware('staff.permission:Hostel Notice Board,add')->name('hostel-management.notices.store');
    Route::patch('/hostel-management/notices/{hostelNotice}', [HostelManagementController::class, 'updateNotice'])->middleware('staff.permission:Hostel Notice Board,edit')->name('hostel-management.notices.update');
    Route::delete('/hostel-management/notices/{hostelNotice}', [HostelManagementController::class, 'destroyNotice'])->middleware('staff.permission:Hostel Notice Board,delete')->name('hostel-management.notices.destroy');
    Route::post('/hostel-management/lost-found', [HostelManagementController::class, 'storeLostFound'])->middleware('staff.permission:Hostel Lost & Found,add')->name('hostel-management.lost-found.store');
    Route::patch('/hostel-management/lost-found/{hostelLostFoundItem}', [HostelManagementController::class, 'updateLostFound'])->middleware('staff.permission:Hostel Lost & Found,edit')->name('hostel-management.lost-found.update');
    Route::patch('/hostel-management/lost-found/{hostelLostFoundItem}/status', [HostelManagementController::class, 'updateLostFoundStatus'])->middleware('staff.permission:Hostel Lost & Found,edit')->name('hostel-management.lost-found.status');
    Route::delete('/hostel-management/lost-found/{hostelLostFoundItem}', [HostelManagementController::class, 'destroyLostFound'])->middleware('staff.permission:Hostel Lost & Found,delete')->name('hostel-management.lost-found.destroy');
    Route::get('/my-hostel', [HostelManagementController::class, 'studentHostel'])->name('student.hostel');
    Route::post('/my-hostel/lost-found', [HostelManagementController::class, 'storeStudentLostFound'])->name('student.hostel.lost-found.store');
    Route::get('/hostel-fee-collection', [HostelManagementController::class, 'feeCollection'])->middleware('staff.permission:Hostel Fee Collection,view')->name('hostel-fee-collection');
    Route::post('/hostel-management/fee-payments', [HostelManagementController::class, 'collectFeePayment'])->middleware('staff.permission:Hostel Fee Collection,add')->name('hostel-management.fee-payments.store');
    Route::post('/hostel-management/fee-payments/{feePayment}/revert', [HostelManagementController::class, 'revertFeePayment'])->middleware('staff.permission:Hostel Fee Collection,edit')->name('hostel-management.fee-payments.revert');
    Route::delete('/hostel-management/fees/{studentFee}', [HostelManagementController::class, 'destroyFeeRecord'])->middleware('staff.permission:Hostel Fee Collection,delete')->name('hostel-management.fees.destroy');
    Route::get('/transport-management', [TransportManagementController::class, 'index'])->middleware('staff.permission:Transport Management,view')->name('transport-management');
    Route::get('/transport-fee-collection', [TransportManagementController::class, 'feeCollection'])->middleware('staff.permission:Transport Fee Collection,view')->name('transport-fee-collection');
    Route::post('/transport-management/routes', [TransportManagementController::class, 'storeRoute'])->middleware('staff.permission:Transport Management,add')->name('transport-management.routes.store');
    Route::put('/transport-management/routes/{id}', [TransportManagementController::class, 'updateRoute'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.routes.update');
    Route::delete('/transport-management/routes/{id}', [TransportManagementController::class, 'deleteRoute'])->middleware('staff.permission:Transport Management,delete')->name('transport-management.routes.destroy');

    Route::post('/transport-management/vehicles', [TransportManagementController::class, 'storeVehicle'])->middleware('staff.permission:Transport Management,add')->name('transport-management.vehicles.store');
    Route::put('/transport-management/vehicles/{id}', [TransportManagementController::class, 'updateVehicle'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.vehicles.update');
    Route::delete('/transport-management/vehicles/{id}', [TransportManagementController::class, 'deleteVehicle'])->middleware('staff.permission:Transport Management,delete')->name('transport-management.vehicles.destroy');

    Route::post('/transport-management/assignments', [TransportManagementController::class, 'storeAssignment'])->middleware('staff.permission:Transport Management,add')->name('transport-management.assignments.store');
    Route::put('/transport-management/assignments/{id}', [TransportManagementController::class, 'updateAssignment'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.assignments.update');
    Route::delete('/transport-management/assignments/{id}', [TransportManagementController::class, 'deleteAssignment'])->middleware('staff.permission:Transport Management,delete')->name('transport-management.assignments.destroy');
    Route::post('/transport-management/fee-payments/bulk', [TransportManagementController::class, 'collectBulkFeePayment'])->middleware('staff.permission:Transport Fee Collection,add')->name('transport-management.fee-payments.bulk-store');
    Route::post('/transport-management/fee-payments/{feePayment}/revert', [TransportManagementController::class, 'revertFeePayment'])->middleware('staff.permission:Transport Fee Collection,edit')->name('transport-management.fee-payments.revert');

    Route::post('/transport-management/trips', [TransportManagementController::class, 'storeTrip'])->middleware('staff.permission:Transport Management,add')->name('transport-management.trips.store');
    Route::put('/transport-management/trips/{id}', [TransportManagementController::class, 'updateTrip'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.trips.update');
    Route::delete('/transport-management/trips/{id}', [TransportManagementController::class, 'deleteTrip'])->middleware('staff.permission:Transport Management,delete')->name('transport-management.trips.destroy');
    Route::post('/transport-management/journeys/start', [TransportManagementController::class, 'startJourney'])->middleware('staff.permission:Transport Management,add')->name('transport-management.journeys.start');
    Route::patch('/transport-management/journeys/{dailyTrip}/stop', [TransportManagementController::class, 'updateReachedStop'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.journeys.stop');
    Route::patch('/transport-management/journeys/{dailyTrip}/end', [TransportManagementController::class, 'endJourney'])->middleware('staff.permission:Transport Management,edit')->name('transport-management.journeys.end');
    Route::get('/attendance', [AttendanceController::class, 'index'])->middleware('staff.permission:Attendance Management,view')->name('attendance');
    Route::post('/attendance', [AttendanceController::class, 'store'])->middleware('staff.permission:Attendance Management,add')->name('attendance.store');
    Route::get('/exams', [ExamController::class, 'index'])->middleware('staff.permission:Exam Management,view')->name('exams');
    Route::get('/exams/hall-ticket', [ExamController::class, 'hallTicket'])->middleware('staff.permission:Hall Ticket,view')->name('exams.hall-ticket');
    Route::get('/exams/print-marksheet', [ExamController::class, 'printMarksheet'])->middleware('staff.permission:Print Marksheet,view')->name('exams.print-marksheet');
    Route::get('/exams/report-card', [ReportCardController::class, 'index'])->middleware('staff.permission:Exam Management,view')->name('exams.report-card');
    Route::post('/exams/report-card/grading-scale', [ReportCardController::class, 'saveGradeScale'])->middleware('staff.permission:Exam Management,edit')->name('exams.report-card.grading-scale');
    Route::get('/offline-exams', [ExamController::class, 'studentOfflineExams'])->name('offline-exams');
    Route::post('/exams', [ExamController::class, 'store'])->middleware('staff.permission:Exam Management,add')->name('exams.store');
    Route::patch('/exams/{exam}', [ExamController::class, 'update'])->middleware('staff.permission:Exam Management,edit')->name('exams.update');
    Route::post('/exams/{exam}/schedules', [ExamController::class, 'saveSchedules'])->middleware('staff.permission:Exam Management,edit')->name('exams.schedules.save');
    Route::post('/exams/schedules/{examSchedule}/results', [ExamController::class, 'saveResults'])->middleware('staff.permission:Exam Management,edit')->name('exams.results.save');
    Route::delete('/exams/{exam}', [ExamController::class, 'destroy'])->middleware('staff.permission:Exam Management,delete')->name('exams.destroy');
    Route::get('/online-exams', [OnlineExamController::class, 'index'])->middleware('staff.permission:Online Exams,view')->name('online-exams');
    Route::post('/online-exams', [OnlineExamController::class, 'store'])->middleware('staff.permission:Online Exams,add')->name('online-exams.store');
    Route::patch('/online-exams/{onlineExam}', [OnlineExamController::class, 'update'])->middleware('staff.permission:Online Exams,edit')->name('online-exams.update');
    Route::delete('/online-exams/{onlineExam}', [OnlineExamController::class, 'destroy'])->middleware('staff.permission:Online Exams,delete')->name('online-exams.destroy');
    Route::post('/online-exams/{onlineExam}/submit', [OnlineExamController::class, 'submit'])->name('online-exams.submit');
    Route::get('/online-exams/results/{attemptId}', [OnlineExamController::class, 'result'])->name('online-exams.result');
    Route::get('/library', [LibraryController::class, 'index'])->middleware('staff.permission:Library Management,view')->name('library');
    Route::get('/inventory', [InventoryController::class, 'index'])->middleware('staff.permission:Inventory Management,view')->name('inventory');
    Route::post('/inventory/categories', [InventoryController::class, 'storeCategory'])->middleware('staff.permission:Inventory Management,add')->name('inventory.categories.store');
    Route::patch('/inventory/categories/{category}', [InventoryController::class, 'updateCategory'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.categories.update');
    Route::delete('/inventory/categories/{category}', [InventoryController::class, 'destroyCategory'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.categories.destroy');
    Route::post('/inventory/stores', [InventoryController::class, 'storeStore'])->middleware('staff.permission:Inventory Management,add')->name('inventory.stores.store');
    Route::patch('/inventory/stores/{store}', [InventoryController::class, 'updateStore'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.stores.update');
    Route::delete('/inventory/stores/{store}', [InventoryController::class, 'destroyStore'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.stores.destroy');
    Route::post('/inventory/suppliers', [InventoryController::class, 'storeSupplier'])->middleware('staff.permission:Inventory Management,add')->name('inventory.suppliers.store');
    Route::patch('/inventory/suppliers/{supplier}', [InventoryController::class, 'updateSupplier'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.suppliers.update');
    Route::delete('/inventory/suppliers/{supplier}', [InventoryController::class, 'destroySupplier'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.suppliers.destroy');
    Route::post('/inventory/items', [InventoryController::class, 'storeItem'])->middleware('staff.permission:Inventory Management,add')->name('inventory.items.store');
    Route::patch('/inventory/items/{item}', [InventoryController::class, 'updateItem'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.items.update');
    Route::delete('/inventory/items/{item}', [InventoryController::class, 'destroyItem'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.items.destroy');
    Route::post('/inventory/stocks', [InventoryController::class, 'storeStock'])->middleware('staff.permission:Inventory Management,add')->name('inventory.stocks.store');
    Route::patch('/inventory/stocks/{stockEntry}', [InventoryController::class, 'updateStock'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.stocks.update');
    Route::delete('/inventory/stocks/{stockEntry}', [InventoryController::class, 'destroyStock'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.stocks.destroy');
    Route::post('/inventory/issues', [InventoryController::class, 'issueItem'])->middleware('staff.permission:Inventory Management,add')->name('inventory.issues.store');
    Route::patch('/inventory/issues/{issue}', [InventoryController::class, 'updateIssue'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.issues.update');
    Route::patch('/inventory/issues/{issue}/return', [InventoryController::class, 'returnIssue'])->middleware('staff.permission:Inventory Management,edit')->name('inventory.issues.return');
    Route::delete('/inventory/issues/{issue}', [InventoryController::class, 'destroyIssue'])->middleware('staff.permission:Inventory Management,delete')->name('inventory.issues.destroy');
    Route::post('/library/books', [LibraryController::class, 'storeBook'])->middleware('staff.permission:Library Management,add')->name('library.books.store');
    Route::patch('/library/books/{book}', [LibraryController::class, 'updateBook'])->middleware('staff.permission:Library Management,edit')->name('library.books.update');
    Route::delete('/library/books/{book}', [LibraryController::class, 'destroyBook'])->middleware('staff.permission:Library Management,delete')->name('library.books.destroy');
    Route::post('/library/books/import', [LibraryController::class, 'importBooks'])->middleware('staff.permission:Library Management,add')->name('library.books.import');
    Route::post('/library/members/{memberKey}/card', [LibraryController::class, 'generateCard'])->middleware('staff.permission:Library Management,edit')->name('library.members.card');
    Route::post('/library/circulation', [LibraryController::class, 'issueBook'])->middleware('staff.permission:Library Management,add')->name('library.circulation.store');
    Route::post('/library/circulation/{circulation}/return', [LibraryController::class, 'returnBook'])->middleware('staff.permission:Library Management,edit')->name('library.circulation.return');
    Route::post('/library/requests', [LibraryController::class, 'storeRequest'])->middleware('staff.permission:Library Management,add')->name('library.requests.store');
    Route::get('/certificates', [CertificateController::class, 'index'])->middleware('staff.permission:Certificate Management,view')->name('certificates');
    Route::get('/my-certificates', [CertificateController::class, 'studentCertificates'])->name('student.certificates');
    Route::post('/certificates/templates', [CertificateController::class, 'store'])->middleware('staff.permission:Certificate Management,add')->name('certificates.templates.store');
    Route::patch('/certificates/templates/{certificateTemplate}', [CertificateController::class, 'update'])->middleware('staff.permission:Certificate Management,edit')->name('certificates.templates.update');
    Route::delete('/certificates/templates/{certificateTemplate}', [CertificateController::class, 'destroy'])->middleware('staff.permission:Certificate Management,delete')->name('certificates.templates.destroy');
    Route::delete('/certificates/issued/{issuedCertificate}', [CertificateController::class, 'destroyIssued'])->middleware('staff.permission:Certificate Management,delete')->name('certificates.issued.destroy');
    Route::post('/certificates/issue-bulk', [CertificateController::class, 'bulkIssue'])->middleware('staff.permission:Certificate Management,add')->name('certificates.issue-bulk');
    Route::get('/certificates/marksheet', [CertificateController::class, 'marksheet'])->middleware('staff.permission:Marksheet Management,view')->name('certificates.marksheet');
    Route::get('/certificates/student-id-card', [CertificateController::class, 'studentIdCard'])->middleware('staff.permission:Student ID Card Management,view')->name('certificates.student-id-card');
    Route::get('/feedback', [FeedbackController::class, 'index'])->middleware('staff.permission:Feedback Management,view')->name('feedback');
    Route::post('/feedback', [FeedbackController::class, 'store'])->middleware('staff.permission:Feedback Management,add')->name('feedback.store');
    Route::patch('/feedback/{feedbackCampaign}', [FeedbackController::class, 'update'])->middleware('staff.permission:Feedback Management,edit')->name('feedback.update');
    Route::delete('/feedback/{feedbackCampaign}', [FeedbackController::class, 'destroy'])->middleware('staff.permission:Feedback Management,delete')->name('feedback.destroy');
    Route::post('/feedback/{feedbackCampaign}/submit', [FeedbackController::class, 'submit'])->name('feedback.submit');
    Route::get('/communication', [CommunicationController::class, 'index'])->middleware('staff.permission:Messages,view')->name('communication');
    Route::post('/communication', [CommunicationController::class, 'storeMessage'])->middleware('staff.permission:Messages,add')->name('communication.store');
    Route::delete('/communication/{message}', [CommunicationController::class, 'destroyMessage'])->middleware('staff.permission:Messages,delete')->name('communication.destroy');
    Route::get('/communication/notice-board', [CommunicationController::class, 'noticeBoard'])->middleware('staff.permission:Notice Board,view')->name('communication.notice-board');
    Route::post('/communication/notice-board', [CommunicationController::class, 'storeNotice'])->middleware('staff.permission:Notice Board,add')->name('communication.notice-board.store');
    Route::patch('/communication/notice-board/{message}', [CommunicationController::class, 'updateNotice'])->middleware('staff.permission:Notice Board,edit')->name('communication.notice-board.update');
    Route::delete('/communication/notice-board/{message}', [CommunicationController::class, 'destroyNotice'])->middleware('staff.permission:Notice Board,delete')->name('communication.notice-board.destroy');
    Route::get('/communication/voice-calls', [CommunicationController::class, 'voiceCalls'])->middleware('staff.permission:Voice Calls,view')->name('communication.voice-calls');
    Route::post('/communication/voice-calls', [CommunicationController::class, 'storeVoiceCall'])->middleware('staff.permission:Voice Calls,add')->name('communication.voice-calls.store');
    Route::patch('/communication/voice-calls/{voiceCallLog}/cancel', [CommunicationController::class, 'cancelVoiceCall'])->middleware('staff.permission:Voice Calls,edit')->name('communication.voice-calls.cancel');
    Route::delete('/communication/voice-calls/{voiceCallLog}', [CommunicationController::class, 'destroyVoiceCall'])->middleware('staff.permission:Voice Calls,delete')->name('communication.voice-calls.destroy');
    Route::get('/communication/voice-calls/{voiceCallLog}/audio', [CommunicationController::class, 'serveVoiceCallAudio'])->middleware('staff.permission:Voice Calls,view')->name('communication.voice-calls.audio');
    Route::get('/communication/send-emails', [CommunicationController::class, 'sendEmails'])->middleware('staff.permission:Send Emails,view')->name('communication.send-emails');
    Route::post('/communication/send-emails', [CommunicationController::class, 'storeEmail'])->middleware('staff.permission:Send Emails,add')->name('communication.send-emails.store');
    Route::delete('/communication/send-emails/{emailLog}', [CommunicationController::class, 'destroyEmail'])->middleware('staff.permission:Send Emails,delete')->name('communication.send-emails.destroy');
    Route::get('/communication/send-sms', [CommunicationController::class, 'sendSms'])->middleware('staff.permission:Send SMS,view')->name('communication.send-sms');
    Route::post('/communication/send-sms', [CommunicationController::class, 'storeSms'])->middleware('staff.permission:Send SMS,add')->name('communication.send-sms.store');
    Route::delete('/communication/send-sms/{smsLog}', [CommunicationController::class, 'destroySms'])->middleware('staff.permission:Send SMS,delete')->name('communication.send-sms.destroy');
    Route::get('/communication/send-whatsapp', [CommunicationController::class, 'sendWhatsapp'])->middleware('staff.permission:Send Whatsapp,view')->name('communication.send-whatsapp');
    Route::post('/communication/send-whatsapp', [CommunicationController::class, 'storeWhatsapp'])->middleware('staff.permission:Send Whatsapp,add')->name('communication.send-whatsapp.store');
    Route::delete('/communication/send-whatsapp/{message}', [CommunicationController::class, 'destroyWhatsapp'])->middleware('staff.permission:Send Whatsapp,delete')->name('communication.send-whatsapp.destroy');
    Route::get('/communication/send-whatsapp/status', [CommunicationController::class, 'whatsappBridgeStatus'])->middleware('staff.permission:Send Whatsapp,view')->name('communication.send-whatsapp.status');
    Route::post('/communication/send-whatsapp/disconnect', [CommunicationController::class, 'disconnectWhatsapp'])->middleware('staff.permission:Send Whatsapp,edit')->name('communication.send-whatsapp.disconnect');
    Route::get('/communication/send-qwa-whatsapp', [CommunicationController::class, 'sendQwaWhatsapp'])->middleware('staff.permission:Send QWA Whatsapp,view')->name('communication.send-qwa-whatsapp');
    Route::post('/communication/send-qwa-whatsapp', [CommunicationController::class, 'storeQwaWhatsapp'])->middleware('staff.permission:Send QWA Whatsapp,add')->name('communication.send-qwa-whatsapp.store');
    Route::get('/communication/send-qwa-whatsapp/status', [CommunicationController::class, 'qwaWhatsappStatus'])->middleware('staff.permission:Send QWA Whatsapp,view')->name('communication.send-qwa-whatsapp.status');
    Route::post('/communication/send-qwa-whatsapp/connect', [CommunicationController::class, 'qwaWhatsappConnect'])->middleware('staff.permission:Send QWA Whatsapp,edit')->name('communication.send-qwa-whatsapp.connect');
    Route::post('/communication/send-qwa-whatsapp/{message}/resend', [CommunicationController::class, 'resendQwaWhatsapp'])->middleware('staff.permission:Send QWA Whatsapp,add')->name('communication.send-qwa-whatsapp.resend');
    Route::delete('/communication/send-qwa-whatsapp/{message}', [CommunicationController::class, 'destroyQwaWhatsapp'])->middleware('staff.permission:Send QWA Whatsapp,delete')->name('communication.send-qwa-whatsapp.destroy');
    Route::get('/communication/download-center', [CommunicationController::class, 'downloadCenter'])->middleware('staff.permission:Download Center,view')->name('communication.download-center');
    Route::post('/communication/download-center/media', [CommunicationController::class, 'storeDownloadCenterMedia'])->middleware('staff.permission:Download Center,add')->name('communication.download-center.media.store');
    Route::post('/communication/download-center/share', [CommunicationController::class, 'storeDownloadCenterShare'])->middleware('staff.permission:Download Center,add')->name('communication.download-center.share.store');
    Route::get('/communication/download-center/shares/{downloadCenterShare}/download', [CommunicationController::class, 'downloadDownloadCenterContent'])->middleware('staff.permission:Download Center,view')->name('communication.download-center.download');
    Route::get('/communication/download-center/shares/{downloadCenterShare}/preview', [CommunicationController::class, 'previewDownloadCenterContent'])->middleware('staff.permission:Download Center,view')->name('communication.download-center.preview');
    Route::get('/todo', [TodoController::class, 'index'])->middleware('staff.permission:Todo,view')->name('todo');
    Route::post('/todo', [TodoController::class, 'store'])->middleware('staff.permission:Todo,add')->name('todo.store');
    Route::patch('/todo/{todo}', [TodoController::class, 'update'])->middleware('staff.permission:Todo,edit')->name('todo.update');
    Route::patch('/todo/{todo}/toggle', [TodoController::class, 'toggle'])->middleware('staff.permission:Todo,edit')->name('todo.toggle');
    Route::delete('/todo/{todo}', [TodoController::class, 'destroy'])->middleware('staff.permission:Todo,delete')->name('todo.destroy');
    Route::get('/reports', [ReportsController::class, 'index'])->middleware('staff.permission:Reports & Analytics,view')->name('reports');
    Route::get('/reports/export-pdf', [ReportsController::class, 'exportPdf'])->middleware('staff.permission:Reports & Analytics,view')->name('reports.export-pdf');
    Route::patch('/reports/sessions/{academicYear}/activate', [SettingsController::class, 'activateSessionAndBack'])->middleware('staff.permission:Sessions,edit')->name('reports.sessions.activate');
    Route::get('/knowledge-base', [SettingsController::class, 'knowledgeBase'])->middleware('staff.permission:Knowledge Base,view')->name('knowledge-base');
    Route::get('/settings', [SettingsController::class, 'index'])->middleware('staff.permission:General Setting,view')->name('settings');
    Route::patch('/settings', [SettingsController::class, 'update'])->middleware('staff.permission:General Setting,edit')->name('settings.update');
    Route::get('/settings/language', [SettingsController::class, 'languageSettings'])->middleware('staff.permission:General Setting,view')->name('settings.language');
    Route::patch('/settings/language', [SettingsController::class, 'updateLanguageSettings'])->middleware('staff.permission:General Setting,edit')->name('settings.language.update');
    Route::post('/settings/translate', [SettingsController::class, 'translateText'])->middleware('staff.permission:General Setting,edit')->name('settings.translate');
    Route::post('/settings/transliterate', [SettingsController::class, 'transliterateText'])->middleware('staff.permission:General Setting,edit')->name('settings.transliterate');
    Route::get('/settings/language-translations', [LanguageTranslationController::class, 'index'])->middleware('staff.permission:General Setting,view')->name('settings.language-translations');
    Route::post('/settings/language-translations', [LanguageTranslationController::class, 'store'])->middleware('staff.permission:General Setting,edit')->name('settings.language-translations.update');
    Route::get('/settings/communication', [SettingsController::class, 'communicationSettings'])->middleware('staff.permission:Communication Setting,view')->name('settings.communication');
    Route::patch('/settings/communication', [SettingsController::class, 'updateCommunicationSettings'])->middleware('staff.permission:Communication Setting,edit')->name('settings.communication.update');
    Route::get('/settings/online-payments', [SettingsController::class, 'onlinePaymentSettings'])->middleware('staff.permission:Online Payment Setting,view')->name('settings.online-payments');
    Route::patch('/settings/online-payments', [SettingsController::class, 'updateOnlinePaymentSettings'])->middleware('staff.permission:Online Payment Setting,edit')->name('settings.online-payments.update');
    Route::get('/settings/sso', [SettingsController::class, 'ssoSettings'])->middleware('staff.permission:SSO Settings,view')->name('settings.sso');
    Route::get('/settings/biometric', [BiometricSettingsController::class, 'index'])->middleware('staff.permission:Biometric Settings,view')->name('settings.biometric');
    Route::post('/settings/biometric/regenerate', [BiometricSettingsController::class, 'regenerate'])->middleware('staff.permission:Biometric Settings,edit')->name('settings.biometric.regenerate');
    Route::get('/settings/biometric/reveal', [BiometricSettingsController::class, 'reveal'])->middleware('staff.permission:Biometric Settings,view')->name('settings.biometric.reveal');
    Route::post('/settings/online-payments/test', [SettingsController::class, 'checkOnlinePayments'])->middleware('staff.permission:Online Payment Setting,view')->name('settings.online-payments.check');
    Route::post('/settings/communication/sms/test', [SettingsController::class, 'sendTestSms'])->middleware('staff.permission:Communication Setting,edit')->name('settings.communication.sms.test');
    Route::post('/settings/communication/qwa/validate', [SettingsController::class, 'validateQwaConnection'])->middleware('staff.permission:Communication Setting,view')->name('settings.communication.qwa.validate');
    Route::post('/settings/communication/qwa/status', [SettingsController::class, 'qwaSessionStatus'])->middleware('staff.permission:Communication Setting,view')->name('settings.communication.qwa.status');
    Route::post('/settings/communication/qwa/start', [SettingsController::class, 'qwaStartSession'])->middleware('staff.permission:Communication Setting,edit')->name('settings.communication.qwa.start');
    Route::get('/settings/roles-permissions', [SettingsController::class, 'rolesPermissions'])->middleware('staff.permission:Roles & Permissions,view')->name('settings.roles-permissions');
    Route::post('/settings/roles', [SettingsController::class, 'storeRole'])->middleware('staff.permission:Roles & Permissions,add')->name('settings.roles.store');
    Route::patch('/settings/roles/{role}', [SettingsController::class, 'updateRole'])->middleware('staff.permission:Roles & Permissions,edit')->name('settings.roles.update');
    Route::delete('/settings/roles/{role}', [SettingsController::class, 'destroyRole'])->middleware('staff.permission:Roles & Permissions,delete')->name('settings.roles.destroy');
    Route::patch('/settings/roles-permissions', [SettingsController::class, 'updateRolesPermissions'])->middleware('staff.permission:Roles & Permissions,edit')->name('settings.roles-permissions.update');
    Route::get('/sessions', [SettingsController::class, 'sessions'])->middleware('staff.permission:Sessions,view')->name('sessions');
    Route::post('/sessions', [SettingsController::class, 'storeSession'])->middleware('staff.permission:Sessions,add')->name('sessions.store');
    Route::patch('/sessions/{academicYear}', [SettingsController::class, 'updateSession'])->middleware('staff.permission:Sessions,edit')->name('sessions.update');
    Route::delete('/sessions/{academicYear}', [SettingsController::class, 'destroySession'])->middleware('staff.permission:Sessions,delete')->name('sessions.destroy');
    Route::patch('/sessions/{academicYear}/activate', [SettingsController::class, 'activateSession'])->middleware('staff.permission:Sessions,edit')->name('sessions.activate');
    Route::get('/events', [EventsController::class, 'index'])->middleware('staff.permission:Events Calendar,view')->name('events');
    Route::post('/events', [EventsController::class, 'store'])->middleware('staff.permission:Events Calendar,add')->name('events.store');
    Route::patch('/events/{schoolEvent}', [EventsController::class, 'update'])->middleware('staff.permission:Events Calendar,edit')->name('events.update');
    Route::delete('/events/{schoolEvent}', [EventsController::class, 'destroy'])->middleware('staff.permission:Events Calendar,delete')->name('events.destroy');
    Route::get('/discipline', [IncidentsController::class, 'index'])->middleware('staff.permission:Discipline,view')->name('discipline');
    Route::post('/discipline', [IncidentsController::class, 'store'])->middleware('staff.permission:Discipline,add')->name('discipline.store');
    Route::patch('/discipline/{incident}', [IncidentsController::class, 'update'])->middleware('staff.permission:Discipline,edit')->name('discipline.update');
    Route::delete('/discipline/{incident}', [IncidentsController::class, 'destroy'])->middleware('staff.permission:Discipline,delete')->name('discipline.destroy');
    Route::get('/student-health', [HealthRecordsController::class, 'index'])->middleware('staff.permission:Student Health,view')->name('student-health');
    Route::post('/student-health', [HealthRecordsController::class, 'store'])->middleware('staff.permission:Student Health,add')->name('student-health.store');
    Route::patch('/student-health/{healthRecord}', [HealthRecordsController::class, 'update'])->middleware('staff.permission:Student Health,edit')->name('student-health.update');
    Route::delete('/student-health/{healthRecord}', [HealthRecordsController::class, 'destroy'])->middleware('staff.permission:Student Health,delete')->name('student-health.destroy');
    Route::get('/attendance-qr', [QrAttendanceController::class, 'index'])->middleware('staff.permission:QR Code Attendance,view')->name('attendance-qr');
    Route::post('/attendance-qr', [QrAttendanceController::class, 'store'])->middleware('staff.permission:QR Code Attendance,add')->name('attendance-qr.store');
    Route::get('/study-materials', [StudyMaterialController::class, 'index'])->middleware('staff.permission:Study Materials,view')->name('study-materials');
    Route::post('/study-materials', [StudyMaterialController::class, 'store'])->middleware('staff.permission:Study Materials,add')->name('study-materials.store');
    Route::patch('/study-materials/{studyMaterial}', [StudyMaterialController::class, 'update'])->middleware('staff.permission:Study Materials,edit')->name('study-materials.update');
    Route::delete('/study-materials/{studyMaterial}', [StudyMaterialController::class, 'destroy'])->middleware('staff.permission:Study Materials,delete')->name('study-materials.destroy');
    Route::get('/study-materials/{studyMaterial}/download', [StudyMaterialController::class, 'download'])->middleware('staff.permission:Study Materials,view')->name('study-materials.download');
    Route::get('/question-bank', [QuestionBankController::class, 'index'])->middleware('staff.permission:Question Bank,view')->name('question-bank');
    Route::post('/question-bank', [QuestionBankController::class, 'store'])->middleware('staff.permission:Question Bank,add')->name('question-bank.store');
    Route::patch('/question-bank/{question}', [QuestionBankController::class, 'update'])->middleware('staff.permission:Question Bank,edit')->name('question-bank.update');
    Route::delete('/question-bank/{question}', [QuestionBankController::class, 'destroy'])->middleware('staff.permission:Question Bank,delete')->name('question-bank.destroy');
    Route::get('/e-library', [EbookLibraryController::class, 'index'])->middleware('staff.permission:E-Library,view')->name('e-library');
    Route::post('/e-library', [EbookLibraryController::class, 'store'])->middleware('staff.permission:E-Library,add')->name('e-library.store');
    Route::patch('/e-library/{ebook}', [EbookLibraryController::class, 'update'])->middleware('staff.permission:E-Library,edit')->name('e-library.update');
    Route::delete('/e-library/{ebook}', [EbookLibraryController::class, 'destroy'])->middleware('staff.permission:E-Library,delete')->name('e-library.destroy');
    Route::get('/e-library/{ebook}/download', [EbookLibraryController::class, 'download'])->middleware('staff.permission:E-Library,view')->name('e-library.download');
    Route::get('/online-classes', [OnlineClassController::class, 'index'])->middleware('staff.permission:Live Online Classes,view')->name('online-classes');
    Route::post('/online-classes', [OnlineClassController::class, 'store'])->middleware('staff.permission:Live Online Classes,add')->name('online-classes.store');
    Route::patch('/online-classes/{onlineClass}', [OnlineClassController::class, 'update'])->middleware('staff.permission:Live Online Classes,edit')->name('online-classes.update');
    Route::patch('/online-classes/{onlineClass}/status', [OnlineClassController::class, 'setStatus'])->middleware('staff.permission:Live Online Classes,edit')->name('online-classes.status');
    Route::delete('/online-classes/{onlineClass}', [OnlineClassController::class, 'destroy'])->middleware('staff.permission:Live Online Classes,delete')->name('online-classes.destroy');
    Route::get('/syllabus', [SyllabusUnitController::class, 'index'])->middleware('staff.permission:Syllabus Coverage,view')->name('syllabus');
    Route::post('/syllabus', [SyllabusUnitController::class, 'store'])->middleware('staff.permission:Syllabus Coverage,add')->name('syllabus.store');
    Route::patch('/syllabus/{syllabusUnit}', [SyllabusUnitController::class, 'update'])->middleware('staff.permission:Syllabus Coverage,edit')->name('syllabus.update');
    Route::patch('/syllabus/{syllabusUnit}/coverage', [SyllabusUnitController::class, 'setCoverage'])->middleware('staff.permission:Syllabus Coverage,edit')->name('syllabus.coverage');
    Route::delete('/syllabus/{syllabusUnit}', [SyllabusUnitController::class, 'destroy'])->middleware('staff.permission:Syllabus Coverage,delete')->name('syllabus.destroy');
    Route::get('/scholarships', [ScholarshipController::class, 'index'])->middleware('staff.permission:Scholarship & Discounts,view')->name('scholarships');
    Route::post('/scholarships', [ScholarshipController::class, 'store'])->middleware('staff.permission:Scholarship & Discounts,add')->name('scholarships.store');
    Route::patch('/scholarships/{scholarship}', [ScholarshipController::class, 'update'])->middleware('staff.permission:Scholarship & Discounts,edit')->name('scholarships.update');
    Route::patch('/scholarships/{scholarship}/toggle', [ScholarshipController::class, 'toggleStatus'])->middleware('staff.permission:Scholarship & Discounts,edit')->name('scholarships.toggle');
    Route::delete('/scholarships/{scholarship}', [ScholarshipController::class, 'destroy'])->middleware('staff.permission:Scholarship & Discounts,delete')->name('scholarships.destroy');
    Route::get('/tally', [TallyExportController::class, 'index'])->middleware('staff.permission:Tally Export,view')->name('tally');
    Route::get('/tally/csv', [TallyExportController::class, 'exportCsv'])->middleware('staff.permission:Tally Export,view')->name('tally.csv');
    Route::get('/tally/xml', [TallyExportController::class, 'exportXml'])->middleware('staff.permission:Tally Export,view')->name('tally.xml');
    Route::get('/helpdesk', [HelpdeskController::class, 'index'])->name('helpdesk');
    Route::post('/helpdesk', [HelpdeskController::class, 'store'])->name('helpdesk.store');
    Route::patch('/helpdesk/{ticket}', [HelpdeskController::class, 'update'])->name('helpdesk.update');
    Route::post('/helpdesk/{ticket}/reply', [HelpdeskController::class, 'reply'])->name('helpdesk.reply');
    Route::get('/chat', [ChatController::class, 'index'])->name('chat');
    Route::get('/chat/data', [ChatController::class, 'data'])->name('chat.data');
    Route::post('/chat/send', [ChatController::class, 'send'])->name('chat.send');
    Route::post('/chat/read', [ChatController::class, 'read'])->name('chat.read');
    Route::get('/teacher-evaluations', [TeacherEvaluationController::class, 'index'])->middleware('staff.permission:Teacher Evaluations,view')->name('teacher-evaluations');
    Route::post('/teacher-evaluations', [TeacherEvaluationController::class, 'store'])->middleware('staff.permission:Teacher Evaluations,add')->name('teacher-evaluations.store');
    Route::patch('/teacher-evaluations/{teacherEvaluation}', [TeacherEvaluationController::class, 'update'])->middleware('staff.permission:Teacher Evaluations,edit')->name('teacher-evaluations.update');
    Route::delete('/teacher-evaluations/{teacherEvaluation}', [TeacherEvaluationController::class, 'destroy'])->middleware('staff.permission:Teacher Evaluations,delete')->name('teacher-evaluations.destroy');
    Route::get('/staff/id-cards', [StaffIdCardController::class, 'index'])->middleware('staff.permission:Staff ID Cards,view')->name('staff-id-cards');
    Route::get('/recruitment', [RecruitmentController::class, 'index'])->middleware('staff.permission:Recruitment & Hiring,view')->name('recruitment');
    Route::post('/recruitment', [RecruitmentController::class, 'store'])->middleware('staff.permission:Recruitment & Hiring,add')->name('recruitment.store');
    Route::patch('/recruitment/{position}', [RecruitmentController::class, 'update'])->middleware('staff.permission:Recruitment & Hiring,edit')->name('recruitment.update');
    Route::patch('/recruitment/{position}/status', [RecruitmentController::class, 'toggleStatus'])->middleware('staff.permission:Recruitment & Hiring,edit')->name('recruitment.status');
    Route::delete('/recruitment/{position}', [RecruitmentController::class, 'destroy'])->middleware('staff.permission:Recruitment & Hiring,delete')->name('recruitment.destroy');
    Route::get('/purchase-orders', [PurchaseOrderController::class, 'index'])->middleware('staff.permission:Vendors & Purchase Orders,view')->name('purchase-orders');
    Route::post('/purchase-orders/vendors', [PurchaseOrderController::class, 'storeVendor'])->middleware('staff.permission:Vendors & Purchase Orders,add')->name('purchase-orders.vendors.store');
    Route::patch('/purchase-orders/vendors/{vendor}', [PurchaseOrderController::class, 'updateVendor'])->middleware('staff.permission:Vendors & Purchase Orders,edit')->name('purchase-orders.vendors.update');
    Route::delete('/purchase-orders/vendors/{vendor}', [PurchaseOrderController::class, 'destroyVendor'])->middleware('staff.permission:Vendors & Purchase Orders,delete')->name('purchase-orders.vendors.destroy');
    Route::post('/purchase-orders/store', [PurchaseOrderController::class, 'storeOrder'])->middleware('staff.permission:Vendors & Purchase Orders,add')->name('purchase-orders.store');
    Route::patch('/purchase-orders/{order}/status', [PurchaseOrderController::class, 'setStatus'])->middleware('staff.permission:Vendors & Purchase Orders,edit')->name('purchase-orders.status');
    Route::delete('/purchase-orders/{order}', [PurchaseOrderController::class, 'destroyOrder'])->middleware('staff.permission:Vendors & Purchase Orders,delete')->name('purchase-orders.destroy');
    Route::get('/auto-timetable', [AutoTimetableController::class, 'index'])->middleware('staff.permission:Auto Timetable,view')->name('auto-timetable');
    Route::post('/auto-timetable/generate', [AutoTimetableController::class, 'generate'])->middleware('staff.permission:Auto Timetable,add')->name('auto-timetable.generate');
    Route::post('/auto-timetable/apply', [AutoTimetableController::class, 'apply'])->middleware('staff.permission:Auto Timetable,add')->name('auto-timetable.apply');
    Route::get('/backups', [BackupController::class, 'index'])->name('automated-backups');
    Route::post('/backups/run', [BackupController::class, 'run'])->name('automated-backups.run');
    Route::get('/backups/{file}/download', [BackupController::class, 'download'])->name('automated-backups.download');
    Route::delete('/backups/{file}', [BackupController::class, 'delete'])->name('automated-backups.delete');
    Route::post('/backups/{file}/restore', [BackupController::class, 'restore'])->name('automated-backups.restore');
    Route::get('/ai-assistant', [AiAssistantController::class, 'index'])->middleware('staff.permission:AI Assistant,view')->name('ai-assistant');
    Route::patch('/settings/ai-assistant', [AiAssistantController::class, 'updateSettings'])->middleware('staff.permission:AI Assistant,edit')->name('ai-assistant.settings');
    Route::post('/ai-assistant/ask', [AiAssistantController::class, 'ask'])->middleware('staff.permission:AI Assistant,view')->name('ai-assistant.ask');
    Route::get('/ptm', [PtmController::class, 'index'])->middleware('staff.permission:PTM,view')->name('ptm');
    Route::post('/ptm', [PtmController::class, 'storeSession'])->middleware('staff.permission:PTM,add')->name('ptm.store');
    Route::patch('/ptm/{ptmSession}', [PtmController::class, 'updateSession'])->middleware('staff.permission:PTM,edit')->name('ptm.update');
    Route::delete('/ptm/{ptmSession}', [PtmController::class, 'destroySession'])->middleware('staff.permission:PTM,delete')->name('ptm.destroy');
    Route::post('/ptm/{ptmSession}/appointments', [PtmController::class, 'storeAppointment'])->middleware('staff.permission:PTM,add')->name('ptm.appointments.store');
    Route::patch('/ptm/appointments/{ptmAppointment}', [PtmController::class, 'updateAppointment'])->middleware('staff.permission:PTM,edit')->name('ptm.appointments.update');
    Route::delete('/ptm/appointments/{ptmAppointment}', [PtmController::class, 'destroyAppointment'])->middleware('staff.permission:PTM,delete')->name('ptm.appointments.destroy');
    Route::get('/website-cms', [SettingsController::class, 'websiteCms'])->middleware('staff.permission:Website CMS,view')->name('website-cms');
    Route::get('/website-cms/editor', [SettingsController::class, 'websiteCmsEditor'])->middleware('staff.permission:Website CMS,edit')->name('website-cms.editor');
    Route::patch('/website-cms', [SettingsController::class, 'updateWebsiteCms'])->middleware('staff.permission:Website CMS,edit')->name('website-cms.update');
    Route::post('/website-cms/slider-images', [SettingsController::class, 'storeWebsiteCmsSliderImage'])->middleware('staff.permission:Website CMS,edit')->name('website-cms.slider-images.store');
    Route::delete('/website-cms/slider-images/{index}', [SettingsController::class, 'destroyWebsiteCmsSliderImage'])->middleware('staff.permission:Website CMS,edit')->name('website-cms.slider-images.destroy');
    Route::patch('/website-cms/section', [SettingsController::class, 'updateWebsiteCmsSection'])->middleware('staff.permission:Website CMS,edit')->name('website-cms.section.update');
    Route::post('/upload/image', [UploadController::class, 'storeImage'])->name('upload.image');
    Route::get('/pages-builder', [WebsitePageController::class, 'index'])->middleware('staff.permission:Website Pages,view')->name('pages.index');
    Route::get('/pages-builder/create', [WebsitePageController::class, 'create'])->middleware('staff.permission:Website Pages,add')->name('pages.create');
    Route::post('/pages-builder', [WebsitePageController::class, 'store'])->middleware('staff.permission:Website Pages,add')->name('pages.store');
    Route::get('/pages-builder/{page}/edit', [WebsitePageController::class, 'edit'])->middleware('staff.permission:Website Pages,edit')->name('pages.edit');
    Route::patch('/pages-builder/{page}', [WebsitePageController::class, 'update'])->middleware('staff.permission:Website Pages,edit')->name('pages.update');
    Route::delete('/pages-builder/{page}', [WebsitePageController::class, 'destroy'])->middleware('staff.permission:Website Pages,delete')->name('pages.destroy');
    Route::post('/pages-builder/api', [WebsitePageController::class, 'storeApi'])->middleware('staff.permission:Website Pages,add')->name('pages.store-api');
    Route::patch('/pages-builder/{page}/sections', [WebsitePageController::class, 'updateSections'])->middleware('staff.permission:Website Pages,edit')->name('pages.sections.update');
    Route::patch('/pages-builder/{page}/content', [WebsitePageController::class, 'updateContent'])->middleware('staff.permission:Website Pages,edit')->name('pages.content.update');
    Route::get('/profile', [ProfileController::class, 'index'])->middleware('staff.permission:Profile,view')->name('profile');
    Route::get('/profile/edit', [ProfileController::class, 'edit'])->middleware('staff.permission:Edit Profile,view')->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->middleware('staff.permission:Edit Profile,edit')->name('profile.update');
    Route::post('/profile/email/verify-otp', [ProfileController::class, 'verifyEmailOtp'])->middleware('staff.permission:Edit Profile,edit')->name('profile.email.verify-otp');
    Route::post('/profile/email/resend-otp', [ProfileController::class, 'resendEmailOtp'])->middleware('staff.permission:Edit Profile,edit')->name('profile.email.resend-otp');
    Route::patch('/profile/password', [ProfileController::class, 'updatePassword'])->middleware('staff.permission:Edit Profile,edit')->name('profile.password');
    Route::group(['prefix' => 'superadmin'], function () {
        Route::get('/', [DashboardController::class, 'index'])->name('superadmin.dashboard');
    });
    Route::post('/logout', function () {
        Auth::logout();
        request()->session()->invalidate();
        request()->session()->regenerateToken();

        return redirect('/login');
    })->name('logout');

});
