// AUTO-CONFIGURED sidebar menu for QGurukul (reference topology).
// Preserves all item ids/hrefs/roles/feature/module gates. Labels adopt
// reference-schooladmin labels where the page exists there.
import {
    Archive,
    ArrowDownCircle,
    ArrowLeftRight,
    ArrowUpCircle,
    Award,
    BadgeCheck,
    BadgePercent,
    Banknote,
    BarChart3,
    BedDouble,
    BellRing,
    Blocks,
    Book,
    BookMarked,
    BookOpen,
    BookOpenCheck,
    Bot,
    Boxes,
    Briefcase,
    Building2,
    BusFront,
    Calculator,
    CalendarCheck,
    CalendarDays,
    CalendarRange,
    CalendarX,
    Camera,
    ClipboardCheck,
    ClipboardList,
    ClipboardPenLine,
    Clock,
    Clock3,
    Compass,
    Contact,
    CreditCard,
    Database,
    DoorOpen,
    Download,
    FileClock,
    FilePlus2,
    FileSpreadsheet,
    FileText,
    Fingerprint,
    FolderOpen,
    FolderTree,
    Gauge,
    GitBranch,
    Globe,
    GraduationCap,
    HandCoins,
    Handshake,
    HardHat,
    Heart,
    HeartPulse,
    HelpCircle,
    History,
    Home,
    IdCard,
    Image,
    Inbox,
    IndianRupee,
    KeyRound,
    Landmark,
    Languages,
    Layers,
    LayoutList,
    LayoutDashboard,
    LayoutTemplate,
    Library,
    LibraryBig,
    LifeBuoy,
    ListChecks,
    Megaphone,
    MessageCircle,
    MessageSquare,
    MonitorPlay,
    Network,
    Package,
    PackageCheck,
    Palette,
    PanelsTopLeft,
    Phone,
    Printer,
    QrCode,
    Rocket,
    ScanFace,
    ScanText,
    School,
    Send,
    Settings,
    Settings2,
    Shapes,
    Share2,
    ShieldAlert,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Tag,
    Tags,
    Target,
    ThumbsUp,
    Trash2,
    TriangleAlert,
    Upload,
    UserCheck,
    UserCog,
    UserPlus,
    UserRound,
    Users,
    Video,
    Wallet,
    Wand2,
    Warehouse,
} from 'lucide-react';

export type SidebarMenuItem = {
    id: string;
    label: string;
    icon: any;
    hub?: boolean;
    roles?: string[];
    feature?: string;
    module?: string;
    href?: string;
    activeMatch?: string[];
    items?: SidebarMenuItem[];
};

export const sidebarConfig: {
    id: string;
    label: string;
    icon: any;
    navMode: 'href' | 'id' | 'href-or-id';
    tabs: string[];
    items: SidebarMenuItem[];
}[] = [
    {
        id: 'dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        navMode: 'href-or-id',
        tabs: ['dashboard'],
        items: [
            {
                id: 'dashboard',
                label: 'Dashboard',
                icon: Home,
                roles: [
                    'super_admin',
                    'admin',
                    'receptionist',
                    'teacher',
                    'accountant',
                    'librarian',
                    'student',
                    'parent',
                ],
                feature: 'Dashboard Home',
            },
        ],
    },
    {
        id: 'erp-navigator',
        label: 'ERP Navigator',
        icon: Compass,
        navMode: 'href-or-id',
        tabs: ['explore'],
        items: [
            {
                id: 'explore',
                label: 'ERP Navigator',
                icon: Compass,
                href: '/explore',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist', 'accountant', 'librarian'],
                feature: 'Dashboard Home',
            },
        ],
    },
    {
        id: 'communicate',
        label: 'Communicate',
        icon: MessageSquare,
        navMode: 'href-or-id',
        tabs: [
            'notifications',
            'communication',
            'send-whatsapp',
            'send-qwa-whatsapp',
            'notice-board',
            'compose-broadcast',
            'broadcast-history',
            'helpdesk',
            'voice-calls',
            'send-emails',
            'send-sms',
            'download-center',
            'document-vault',
            'image-gallery',
            'chat',
        ],
        items: [
            {
                id: 'notifications',
                label: 'Notifications',
                icon: BellRing,
                href: '/notifications',
                roles: [
                    'super_admin',
                    'admin',
                    'teacher',
                    'receptionist',
                    'accountant',
                    'librarian',
                    'student',
                    'parent',
                ],
                feature: 'Dashboard Home',
            },
            {
                id: 'communication',
                label: 'Messages',
                icon: MessageSquare,
                href: '/communication',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist'],
                feature: 'Messages',
            },
            {
                id: 'send-whatsapp',
                label: 'Send Whatsapp',
                icon: MessageSquare,
                href: '/communication/send-whatsapp',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist'],
                feature: 'Send Whatsapp',
            },
            {
                id: 'send-qwa-whatsapp',
                label: 'Send QWA Whatsapp',
                icon: MessageSquare,
                href: '/communication/send-qwa-whatsapp',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist'],
                feature: 'Send QWA Whatsapp',
            },
            {
                id: 'notice-board',
                label: 'Notice Board',
                icon: Award,
                href: '/communication/notice-board',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist', 'student'],
                feature: 'Notice Board',
            },
            {
                id: 'compose-broadcast',
                label: 'Compose Broadcast',
                icon: Megaphone,
                href: '/communicate/broadcast/create',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist'],
                feature: 'Messages',
            },
            {
                id: 'broadcast-history',
                label: 'Broadcast History',
                icon: History,
                href: '/communicate/broadcast',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist'],
                feature: 'Messages',
            },
            {
                id: 'helpdesk',
                label: 'Helpdesk',
                icon: LifeBuoy,
                roles: ['super_admin', 'admin', 'teacher', 'receptionist', 'accountant', 'student'],
                feature: 'Parent Helpdesk',
            },
            {
                id: 'voice-calls',
                label: 'Voice Calls',
                icon: Phone,
                href: '/communication/voice-calls',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist'],
                feature: 'Voice Calls',
            },
            {
                id: 'send-emails',
                label: 'Send Emails',
                icon: Send,
                href: '/communication/send-emails',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist'],
                feature: 'Send Emails',
            },
            {
                id: 'send-sms',
                label: 'Send SMS',
                icon: MessageSquare,
                href: '/communication/send-sms',
                roles: ['super_admin', 'admin', 'teacher', 'parent', 'receptionist', 'accountant'],
                feature: 'Send SMS',
            },
            {
                id: 'download-center',
                label: 'Download Center',
                icon: Download,
                href: '/communication/download-center',
                roles: [
                    'super_admin',
                    'admin',
                    'teacher',
                    'parent',
                    'receptionist',
                    'student',
                    'accountant',
                    'librarian',
                ],
                feature: 'Download Center',
            },
            {
                id: 'document-vault',
                label: 'Document Vault',
                icon: Archive,
                href: '/document-vault',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist', 'accountant', 'librarian', 'student'],
                feature: 'Download Center',
            },
            {
                id: 'image-gallery',
                label: 'Image Gallery',
                icon: Image,
                href: '/gallery',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist', 'accountant', 'librarian', 'student'],
                feature: 'Image Gallery',
            },
            {
                id: 'chat',
                label: 'Live Chat',
                icon: MessageCircle,
                href: '/chat',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist', 'accountant', 'librarian', 'student'],
                feature: 'Live Chat',
            },
        ],
    },
    {
        id: 'study-center',
        label: 'Study Center',
        icon: GraduationCap,
        navMode: 'href-or-id',
        tabs: ['study-materials', 'question-bank', 'classwork-logbook'],
        items: [
            {
                id: 'study-materials',
                label: 'Study Materials',
                icon: FolderOpen,
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Study Materials',
            },
            {
                id: 'question-bank',
                label: 'Question Bank',
                icon: HelpCircle,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Question Bank',
            },
            {
                id: 'classwork-logbook',
                label: 'Classwork & Logbook',
                icon: BookOpenCheck,
                href: '/classwork-logbook',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Homework',
            },
        ],
    },
    {
        id: 'live-classes',
        label: 'Live Classes',
        icon: Video,
        navMode: 'href-or-id',
        tabs: ['online-classes'],
        items: [
            {
                id: 'online-classes',
                label: 'Online Classes',
                icon: Video,
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Live Online Classes',
            },
        ],
    },
    {
        id: 'lesson-planner',
        label: 'Lesson Planner',
        icon: BookOpen,
        navMode: 'href-or-id',
        tabs: ['syllabus'],
        items: [
            {
                id: 'syllabus',
                label: 'Syllabus Coverage',
                icon: BookOpenCheck,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Syllabus Coverage',
            },
        ],
    },
    {
        id: 'student-info',
        label: 'Student Information',
        icon: Users,
        navMode: 'href-or-id',
        tabs: [
            'attendance',
            'student-health',
            'student-dashboard',
            'search_students',
            'online-admission',
            'bulk-delete-students',
            'alumni-records',
            'student-exits',
            'students-recycle-bin',
            'parents',
            'houses-categories',
            'face-search',
        ],
        items: [
            {
                id: 'attendance',
                label: 'Attendance',
                icon: CalendarCheck,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Attendance Management',
            },
            {
                id: 'student-health',
                label: 'Health Records',
                icon: HeartPulse,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Student Health',
            },
            {
                id: 'student-dashboard',
                label: 'Student Dashboard',
                icon: Users,
                href: '/student-dashboard',
                roles: ['super_admin', 'admin', 'receptionist', 'teacher'],
                feature: 'Search Students',
            },
            {
                id: 'search_students',
                label: 'Search Students',
                icon: Users,
                href: '/search_students',
                roles: ['super_admin', 'admin', 'receptionist', 'teacher'],
                feature: 'Search Students',
            },
            {
                id: 'online-admission',
                label: 'Online Admission',
                icon: FileText,
                href: '/online-admission',
                roles: ['super_admin', 'admin', 'receptionist', 'teacher'],
                feature: 'Online Admission',
            },
            {
                id: 'bulk-delete-students',
                label: 'Bulk Delete',
                icon: Trash2,
                href: '/bulk-delete-students',
                roles: ['super_admin', 'admin', 'receptionist', 'teacher'],
                feature: 'Bulk Delete Students',
            },
            {
                id: 'alumni-records',
                label: 'Alumni Records',
                icon: GraduationCap,
                href: '/alumni-records',
                roles: ['super_admin', 'admin', 'receptionist', 'teacher'],
                feature: 'Alumni Records',
            },
            {
                id: 'student-exits',
                label: 'TC & Exit',
                icon: ClipboardList,
                href: '/student-exits',
                roles: ['super_admin', 'admin'],
                feature: 'TC & Exit',
            },
            {
                id: 'students-recycle-bin',
                label: 'Students Recycle Bin',
                icon: Trash2,
                href: '/students-recycle-bin',
                roles: ['super_admin', 'admin'],
                feature: 'Search Students',
            },
            {
                id: 'parents',
                label: 'Parents & Guardians',
                icon: Users,
                href: '/parents',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist'],
                feature: 'Search Students',
            },
            {
                id: 'houses-categories',
                label: 'Houses & Categories',
                icon: Palette,
                href: '/houses-categories',
                roles: ['super_admin', 'admin'],
                feature: 'Search Students',
            },
            {
                id: 'face-search',
                label: 'Face Search',
                icon: ScanFace,
                href: '/face-search',
                roles: ['super_admin', 'admin'],
                feature: 'Search Students',
                module: 'face-search',
            },
        ],
    },
    {
        id: 'qr-attendance',
        label: 'QR Code Attendance',
        icon: QrCode,
        navMode: 'href-or-id',
        tabs: ['attendance-qr'],
        items: [
            {
                id: 'attendance-qr',
                label: 'QR Attendance',
                icon: QrCode,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'QR Code Attendance',
            },
        ],
    },
    {
        id: 'finance',
        label: 'Finance & Fees',
        icon: Wallet,
        navMode: 'href-or-id',
        tabs: [
            'fees-dashboard',
            'fees',
            'fee-challans',
            'assign-fees',
            'due-slips',
            'fee-audit',
            'fee-groups',
            'fees-discounts',
            'scholarships',
            'all-transactions',
        ],
        items: [
            {
                id: 'fees-dashboard',
                label: 'Fees Dashboard',
                icon: IndianRupee,
                href: '/fees/dashboard',
                roles: ['super_admin', 'admin', 'accountant', 'receptionist'],
                feature: 'Fees Management',
            },
            {
                id: 'fees',
                label: 'Fees',
                icon: IndianRupee,
                roles: ['super_admin', 'admin', 'accountant', 'receptionist', 'student'],
                feature: 'Fees Management',
            },
            {
                id: 'fee-challans',
                label: 'Fee Challans',
                icon: FileText,
                href: '/fees/challans',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'assign-fees',
                label: 'Assign Fees',
                icon: UserCheck,
                href: '/assign-fees',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'due-slips',
                label: 'Due Slips',
                icon: FileText,
                href: '/fees/due-slips',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'fee-audit',
                label: 'Fee Audit',
                icon: FileClock,
                href: '/fees/audit',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'fee-groups',
                label: 'Fee Groups',
                icon: Layers,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'fees-discounts',
                label: 'Fees Discount',
                icon: BadgePercent,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Fees Management',
            },
            {
                id: 'scholarships',
                label: 'Scholarships',
                icon: BadgePercent,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Scholarship & Discounts',
            },
            {
                id: 'all-transactions',
                label: 'All Transactions',
                icon: ArrowLeftRight,
                href: '/all-transactions',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Bank Accounts',
            },
        ],
    },
    {
        id: 'accounts',
        label: 'Accounts',
        icon: Calculator,
        navMode: 'href-or-id',
        tabs: [
            'tally',
            'accounts-dashboard',
            'income-management',
            'expense-management',
            'income-heads',
            'expense-heads',
            'bank-accounts',
        ],
        items: [
            {
                id: 'tally',
                label: 'Tally Export',
                icon: FileSpreadsheet,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Tally Export',
            },
            {
                id: 'accounts-dashboard',
                label: 'Accounts Dashboard',
                icon: Landmark,
                href: '/accounting/dashboard',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Income Management',
            },
            {
                id: 'income-management',
                label: 'Income',
                icon: ArrowUpCircle,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Income Management',
            },
            {
                id: 'expense-management',
                label: 'Expense',
                icon: ArrowDownCircle,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Expense Management',
            },
            {
                id: 'income-heads',
                label: 'Income Heads',
                icon: Tags,
                href: '/accounts/income-heads',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Income Management',
            },
            {
                id: 'expense-heads',
                label: 'Expense Heads',
                icon: Tag,
                href: '/accounts/expense-heads',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Expense Management',
            },
            {
                id: 'bank-accounts',
                label: 'Bank Accounts',
                icon: Landmark,
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Bank Accounts',
            },
        ],
    },
    {
        id: 'settings',
        label: 'Settings & Billing',
        icon: Settings,
        navMode: 'href-or-id',
        tabs: [
            'subscription',
            'payment-history',
            'profile',
            'settings',
            'language-settings',
            'communication-settings',
            'social-media-settings',
            'telegram-settings',
            'online-payment-settings',
            'sso-settings',
            'hr-settings',
            'roles-permissions',
            'automated-backups',
            'custom-fields',
            'admission-settings',
            'ai-assistant',
            'module-management',
            'dashboard-themes',
            'branch-admin',
        ],
        items: [
            {
                id: 'subscription',
                label: 'Subscription',
                icon: Rocket,
                href: '/subscription',
                roles: ['super_admin', 'admin'],
                feature: 'Subscription Management',
            },
            {
                id: 'payment-history',
                label: 'Subscription History',
                icon: History,
                href: '/payment-history',
                roles: ['super_admin', 'admin'],
                feature: 'Subscription Management',
            },
            {
                id: 'profile',
                label: 'Profile',
                icon: UserRound,
                href: '/profile',
                roles: [
                    'super_admin',
                    'admin',
                    'receptionist',
                    'teacher',
                    'accountant',
                    'librarian',
                    'student',
                    'parent',
                ],
                feature: 'Profile',
            },
            {
                id: 'settings',
                label: 'General Setting',
                icon: Settings,
                href: '/settings',
                roles: ['admin'],
                feature: 'General Setting',
            },
            {
                id: 'language-settings',
                label: 'Language Setting',
                icon: Languages,
                href: '/settings/language',
                roles: ['admin'],
                feature: 'General Setting',
            },
            {
                id: 'communication-settings',
                label: 'Communication Setting',
                icon: MessageSquare,
                href: '/settings/communication',
                roles: ['admin'],
                feature: 'Communication Setting',
            },
            {
                id: 'social-media-settings',
                label: 'Social Media Autopost',
                icon: Share2,
                href: '/settings/social-media',
                roles: ['admin'],
                feature: 'Communication Setting',
            },
            {
                id: 'telegram-settings',
                label: 'Telegram Bot',
                icon: Send,
                href: '/settings/telegram',
                roles: ['admin'],
                feature: 'Communication Setting',
            },
            {
                id: 'online-payment-settings',
                label: 'Online Payments',
                icon: CreditCard,
                href: '/settings/online-payments',
                roles: ['admin'],
                feature: 'Online Payment Setting',
            },
            {
                id: 'sso-settings',
                label: 'SSO Settings',
                icon: KeyRound,
                href: '/settings/sso',
                roles: ['super_admin', 'admin'],
                feature: 'SSO Settings',
            },
            {
                id: 'hr-settings',
                label: 'HR / Payroll Settings',
                icon: Settings2,
                href: '/settings/hr',
                roles: ['admin'],
                feature: 'User Management',
            },
            {
                id: 'roles-permissions',
                label: 'Roles & Permissions',
                icon: ShieldCheck,
                href: '/settings/roles-permissions',
                roles: ['admin'],
                feature: 'Roles & Permissions',
            },
            {
                id: 'automated-backups',
                label: 'Database Backups',
                icon: Database,
                href: '/backups',
                roles: ['super_admin', 'admin'],
                feature: 'General Setting',
            },
            {
                id: 'custom-fields',
                label: 'Custom Fields',
                icon: ClipboardList,
                href: '/custom-fields',
                roles: ['admin'],
                feature: 'General Setting',
            },
            {
                id: 'admission-settings',
                label: 'Admission Settings',
                icon: FilePlus2,
                href: '/admission-settings',
                roles: ['admin'],
                feature: 'General Setting',
            },
            {
                id: 'ai-assistant',
                label: 'AI Assistant',
                icon: Bot,
                href: '/ai-assistant',
                roles: ['super_admin', 'admin'],
                feature: 'AI Assistant',
            },
            {
                id: 'module-management',
                label: 'Module Management',
                icon: Blocks,
                href: '/module-management',
                roles: ['admin'],
                feature: 'Module Management',
            },
            {
                id: 'dashboard-themes',
                label: 'Dashboard Themes',
                icon: Palette,
                href: '/settings/themes',
                roles: ['admin'],
                feature: 'General Setting',
                module: 'dashboard-themes',
            },
            {
                id: 'branch-admin',
                label: 'Branch Admin',
                icon: Network,
                href: '/branch-admin',
                roles: ['super_admin'],
                feature: 'Branch Admin',
                module: 'branch-admin',
            },
        ],
    },
    {
        id: 'chat-moderation',
        label: 'Chat Moderation',
        icon: ShieldAlert,
        navMode: 'href-or-id',
        tabs: ['nsfw', 'chat-moderation'],
        items: [
            {
                id: 'nsfw',
                label: 'Content Safety',
                icon: ShieldAlert,
                href: '/nsfw',
                roles: ['super_admin', 'admin'],
                feature: 'Content Safety',
            },
            {
                id: 'chat-moderation',
                label: 'Chat Moderation',
                icon: ShieldAlert,
                href: '/chat-moderation',
                roles: ['admin'],
                feature: 'Live Chat',
            },
        ],
    },
    {
        id: 'asset-management',
        label: 'Asset Management',
        icon: Boxes,
        navMode: 'href-or-id',
        tabs: ['asset-dashboard', 'assets'],
        items: [
            {
                id: 'asset-dashboard',
                label: 'Asset Dashboard',
                icon: Gauge,
                href: '/assets/dashboard',
                roles: ['super_admin', 'admin'],
                feature: 'Asset Management',
                module: 'assets',
            },
            {
                id: 'assets',
                label: 'Assets',
                icon: Warehouse,
                href: '/assets',
                roles: ['super_admin', 'admin'],
                feature: 'Asset Management',
                module: 'assets',
            },
        ],
    },
    {
        id: 'online-exams',
        label: 'Online Examinations',
        icon: MonitorPlay,
        navMode: 'href-or-id',
        tabs: ['online-exam-dashboard', 'online-exams'],
        items: [
            {
                id: 'online-exam-dashboard',
                label: 'Online Exam Dashboard',
                icon: Globe,
                href: '/online-exam/dashboard',
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Online Exams',
            },
            {
                id: 'online-exams',
                label: 'Online Exams',
                icon: Clock3,
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Online Exams',
            },
        ],
    },
    {
        id: 'offline-exams',
        label: 'Offline Examinations',
        icon: FileText,
        navMode: 'href-or-id',
        tabs: [
            'offline-exams',
            'exam-dashboard',
            'examination',
            'datesheets',
            'exam-types',
            'manage-grades',
            'enter-marks',
            'exam-schedule-setup',
            'hall-ticket',
            'print-marksheet',
            'report-card',
            'marksheet-remarks',
        ],
        items: [
            {
                id: 'offline-exams',
                label: 'Offline Exams',
                icon: FileText,
                roles: ['student'],
                feature: 'Exam Management',
            },
            {
                id: 'exam-dashboard',
                label: 'Exam Dashboard',
                icon: FileText,
                href: '/exams-dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'examination',
                label: 'Examination',
                icon: FileText,
                href: '/exams',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'datesheets',
                label: 'Datesheet',
                icon: CalendarRange,
                href: '/datesheets',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'exam-types',
                label: 'Exam Types',
                icon: ShieldCheck,
                href: '/exam-types',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'manage-grades',
                label: 'Manage Grades',
                icon: BookMarked,
                href: '/grades',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'enter-marks',
                label: 'Enter Marks',
                icon: ClipboardList,
                href: '/exams/marks/entry',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'exam-schedule-setup',
                label: 'Schedule Setup',
                icon: CalendarRange,
                href: '/exam-schedule',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'hall-ticket',
                label: 'Hall Ticket',
                icon: BookOpen,
                href: '/exams/hall-ticket',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Hall Ticket',
            },
            {
                id: 'print-marksheet',
                label: 'Print Marksheet',
                icon: Award,
                href: '/exams/print-marksheet',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Print Marksheet',
            },
            {
                id: 'report-card',
                label: 'Report Card',
                icon: FileText,
                href: '/exams/report-card',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Report Card',
            },
            {
                id: 'marksheet-remarks',
                label: 'Enter Report Card Remarks',
                icon: MessageSquare,
                href: '/marksheet-remarks',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
        ],
    },
    {
        id: 'surveys',
        label: 'Surveys & Feedback',
        icon: ThumbsUp,
        navMode: 'href-or-id',
        tabs: ['feedback', 'survey-dashboard', 'surveys'],
        items: [
            {
                id: 'feedback',
                label: 'Feedback',
                icon: ClipboardPenLine,
                roles: ['admin', 'student'],
                feature: 'Feedback Management',
            },
            {
                id: 'survey-dashboard',
                label: 'Survey Dashboard',
                icon: Send,
                href: '/survey/dashboard',
                roles: ['admin', 'student'],
                feature: 'Feedback Management',
            },
            {
                id: 'surveys',
                label: 'Surveys',
                icon: ClipboardPenLine,
                href: '/surveys',
                roles: ['admin'],
                feature: 'Feedback Management',
            },
        ],
    },
    {
        id: 'hostel',
        label: 'Hostel',
        icon: BedDouble,
        navMode: 'href-or-id',
        tabs: [
            'my-hostel',
            'hostel-dashboard',
            'hostel-management',
            'hostel-room-types',
            'hostel-allocations',
            'hostel-fee-collection',
        ],
        items: [
            {
                id: 'my-hostel',
                label: 'Hostel',
                icon: BedDouble,
                href: '/my-hostel',
                roles: ['student'],
                feature: 'Dashboard Home',
            },
            {
                id: 'hostel-dashboard',
                label: 'Hostel Dashboard',
                icon: BedDouble,
                href: '/hostel/dashboard',
                roles: ['admin'],
                feature: 'Hostel Management',
            },
            {
                id: 'hostel-management',
                label: 'Manage Hostel',
                icon: BedDouble,
                href: '/hostel-management',
                roles: ['admin'],
                feature: 'Hostel Management',
            },
            {
                id: 'hostel-room-types',
                label: 'Room Types',
                icon: BedDouble,
                href: '/hostel/room-types',
                roles: ['super_admin', 'admin'],
                feature: 'Hostel Management',
            },
            {
                id: 'hostel-allocations',
                label: 'Student Allocation',
                icon: BedDouble,
                href: '/hostel/allocations',
                roles: ['super_admin', 'admin'],
                feature: 'Hostel Management',
            },
            {
                id: 'hostel-fee-collection',
                label: 'Fee Collection',
                icon: IndianRupee,
                href: '/hostel-fee-collection',
                roles: ['admin'],
                feature: 'Hostel Fee Collection',
            },
        ],
    },
    {
        id: 'front-office',
        label: 'Front Office',
        icon: Briefcase,
        navMode: 'href-or-id',
        tabs: [
            'complains',
            'front-office-dashboard',
            'admission-enquiry',
            'visitor-register',
            'gate-passes',
            'phone-call-log',
            'postal-dispatch',
            'postal-delivery',
            'campus-workers',
        ],
        items: [
            {
                id: 'complains',
                label: 'Complaints',
                icon: TriangleAlert,
                roles: ['student'],
                feature: 'Complains',
            },
            {
                id: 'front-office-dashboard',
                label: 'Front Office Dashboard',
                icon: Briefcase,
                href: '/front-office/dashboard',
                roles: ['admin', 'receptionist'],
                feature: 'Admission Enquiry',
            },
            {
                id: 'admission-enquiry',
                label: 'Admission Enquiry',
                icon: UserRound,
                roles: ['admin', 'receptionist'],
                feature: 'Admission Enquiry',
            },
            {
                id: 'visitor-register',
                label: 'Visitor Register',
                icon: Briefcase,
                roles: ['admin', 'receptionist'],
                feature: 'Visitor Register',
            },
            {
                id: 'gate-passes',
                label: 'Gate Passes',
                icon: DoorOpen,
                roles: ['admin', 'receptionist', 'super_admin'],
                feature: 'Visitor Register',
            },
            {
                id: 'phone-call-log',
                label: 'Phone Call Log',
                icon: Phone,
                roles: ['admin', 'receptionist'],
                feature: 'Phone Call Log',
            },
            {
                id: 'postal-dispatch',
                label: 'Postal Dispatch',
                icon: Send,
                roles: ['admin', 'receptionist'],
                feature: 'Postal Dispatch',
            },
            {
                id: 'postal-delivery',
                label: 'Postal Delivery',
                icon: Inbox,
                roles: ['admin', 'receptionist'],
                feature: 'Postal Delivery',
            },
            {
                id: 'campus-workers',
                label: 'Campus Workers',
                icon: HardHat,
                href: '/campus-workers',
                roles: ['admin'],
                feature: 'Recruitment & Hiring',
            },
        ],
    },
    {
        id: 'engagement',
        label: 'Engagement',
        icon: Heart,
        navMode: 'href-or-id',
        tabs: ['events-calendar', 'engagement', 'creatives'],
        items: [
            {
                id: 'events-calendar',
                label: 'Events Calendar',
                icon: CalendarDays,
                href: '/events',
                roles: ['super_admin', 'admin', 'teacher', 'receptionist'],
                feature: 'Events Calendar',
            },
            {
                id: 'engagement',
                label: 'Engagement',
                icon: HeartPulse,
                href: '/engagement',
                roles: ['admin'],
                feature: 'Events Calendar',
            },
            {
                id: 'creatives',
                label: 'Creatives',
                icon: Palette,
                href: '/creatives',
                roles: ['admin'],
                feature: 'Events Calendar',
            },
        ],
    },
    {
        id: 'compliance',
        label: 'Compliance & Governance',
        icon: ShieldCheck,
        navMode: 'href-or-id',
        tabs: ['discipline', 'compliance', 'data-validator', 'inspections'],
        items: [
            {
                id: 'discipline',
                label: 'Discipline',
                icon: ShieldAlert,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Discipline',
            },
            {
                id: 'compliance',
                label: 'Compliance Suite',
                icon: ShieldCheck,
                href: '/compliance',
                roles: ['admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'data-validator',
                label: 'Data Validator',
                icon: ShieldCheck,
                href: '/data-validator',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'inspections',
                label: 'Inspections',
                icon: ClipboardCheck,
                href: '/inspections',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
        ],
    },
    {
        id: 'ptm',
        label: 'PTM Meetings',
        icon: Handshake,
        navMode: 'href-or-id',
        tabs: ['ptm-dashboard', 'ptm', 'ptm-guide', 'ptm-reports'],
        items: [
            {
                id: 'ptm-dashboard',
                label: 'PTM Dashboard',
                icon: Handshake,
                href: '/ptm/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'PTM',
            },
            {
                id: 'ptm',
                label: 'Parent-Teacher Meeting',
                icon: Handshake,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'PTM',
            },
            {
                id: 'ptm-guide',
                label: 'PTM Guide',
                icon: Handshake,
                href: '/ptm/guide',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'PTM',
            },
            {
                id: 'ptm-reports',
                label: 'PTM Reports',
                icon: Handshake,
                href: '/ptm/reports',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'PTM',
            },
        ],
    },
    {
        id: 'library',
        label: 'Library',
        icon: Library,
        navMode: 'href-or-id',
        tabs: ['library-dashboard', 'library', 'e-library'],
        items: [
            {
                id: 'library-dashboard',
                label: 'Library Dashboard',
                icon: Book,
                href: '/library/dashboard',
                roles: ['super_admin', 'admin', 'librarian', 'teacher'],
                feature: 'Library Management',
            },
            {
                id: 'library',
                label: 'Library',
                icon: Book,
                roles: ['super_admin', 'admin', 'librarian', 'teacher'],
                feature: 'Library Management',
            },
            {
                id: 'e-library',
                label: 'E-Library',
                icon: LibraryBig,
                roles: ['super_admin', 'admin', 'librarian', 'teacher', 'student'],
                feature: 'E-Library',
            },
        ],
    },
    {
        id: 'inventory',
        label: 'Inventory',
        icon: Package,
        navMode: 'href-or-id',
        tabs: ['inventory-dashboard', 'inventory', 'purchase-orders', 'store-pos', 'store-receipts', 'store-payments'],
        items: [
            {
                id: 'inventory-dashboard',
                label: 'Inventory Dashboard',
                icon: Warehouse,
                href: '/inventory/dashboard',
                roles: ['super_admin', 'admin', 'accountant', 'librarian', 'receptionist'],
                feature: 'Inventory Management',
            },
            {
                id: 'inventory',
                label: 'Inventory',
                icon: Boxes,
                roles: ['super_admin', 'admin', 'accountant', 'librarian', 'receptionist'],
                feature: 'Inventory Management',
            },
            {
                id: 'purchase-orders',
                label: 'Vendors & Orders',
                icon: ShoppingCart,
                href: '/purchase-orders',
                roles: ['super_admin', 'admin', 'accountant'],
                feature: 'Vendors & Purchase Orders',
            },
            {
                id: 'store-pos',
                label: 'Point of Sale',
                icon: ShoppingBag,
                href: '/store/pos',
                roles: ['super_admin', 'admin'],
                feature: 'Vendors & Purchase Orders',
            },
            {
                id: 'store-receipts',
                label: 'Goods Receipts',
                icon: PackageCheck,
                href: '/store/goods-receipts',
                roles: ['super_admin', 'admin'],
                feature: 'Vendors & Purchase Orders',
            },
            {
                id: 'store-payments',
                label: 'Supplier Payments',
                icon: Wallet,
                href: '/store/supplier-payments',
                roles: ['super_admin', 'admin'],
                feature: 'Vendors & Purchase Orders',
            },
        ],
    },
    {
        id: 'apps-center',
        label: 'Apps Center',
        icon: Blocks,
        navMode: 'href-or-id',
        tabs: ['apps-center'],
        items: [
            {
                id: 'apps-center',
                label: 'Apps Center',
                icon: PanelsTopLeft,
                href: '/apps',
                roles: ['super_admin', 'admin'],
                feature: 'Apps Center',
                module: 'apps-center',
            },
        ],
    },
    {
        id: 'help-center',
        label: 'Help Center',
        icon: LifeBuoy,
        navMode: 'href-or-id',
        tabs: ['knowledge-base', 'contact-support'],
        items: [
            {
                id: 'knowledge-base',
                label: 'Knowledge Base',
                icon: BookOpen,
                roles: ['admin', 'teacher', 'receptionist', 'accountant', 'librarian'],
                feature: 'Knowledge Base',
            },
            {
                id: 'contact-support',
                label: 'Contact Support',
                icon: LifeBuoy,
                href: '/contact-support',
                roles: ['admin', 'teacher', 'receptionist', 'accountant', 'librarian', 'parent'],
                feature: 'Knowledge Base',
            },
        ],
    },
    {
        id: 'human-resource',
        label: 'Human Resource',
        icon: UserCog,
        navMode: 'href-or-id',
        tabs: [
            'my-leaves',
            'staff',
            'hr-dashboard',
            'import-center',
            'staff-daily-attendance',
            'payroll-management',
            'leave-management',
            'leave-types',
            'staff-loans',
            'staff-appraisals',
            'salary-templates',
            'recruitment',
            'staff-directory',
        ],
        items: [
            {
                id: 'my-leaves',
                label: 'My Leaves',
                icon: CalendarX,
                href: '/my-leaves',
                roles: ['receptionist', 'teacher', 'accountant', 'librarian'],
                feature: 'My Leaves',
            },
            {
                id: 'staff',
                label: 'Staff Management',
                icon: UserCog,
                href: '/staff',
                roles: ['admin'],
                feature: 'User Management',
            },
            {
                id: 'hr-dashboard',
                label: 'HR Dashboard',
                icon: BarChart3,
                href: '/hr-dashboard',
                roles: ['admin', 'super_admin'],
                feature: 'User Management',
            },
            {
                id: 'import-center',
                label: 'Import Center',
                icon: Upload,
                href: '/import-center',
                roles: ['admin', 'super_admin'],
                feature: 'User Management',
            },
            {
                id: 'staff-daily-attendance',
                label: 'Staff Attendance',
                icon: CalendarCheck,
                href: '/staff/daily-attendance',
                roles: ['admin'],
                feature: 'Staff Attendance',
            },
            {
                id: 'payroll-management',
                label: 'Payroll',
                icon: IndianRupee,
                href: '/staff/payroll-management',
                roles: ['admin'],
                feature: 'Payroll Management',
            },
            {
                id: 'leave-management',
                label: 'Approve Leave',
                icon: CalendarX,
                href: '/staff/leave-management',
                roles: ['admin'],
                feature: 'Leave Management',
            },
            {
                id: 'leave-types',
                label: 'Leave Types',
                icon: CalendarRange,
                href: '/staff/leave-types',
                roles: ['admin'],
                feature: 'Leave Management',
            },
            {
                id: 'staff-loans',
                label: 'Staff Loans',
                icon: HandCoins,
                href: '/staff/loans',
                roles: ['admin'],
                feature: 'Payroll Management',
            },
            {
                id: 'staff-appraisals',
                label: 'Staff Appraisals',
                icon: ClipboardList,
                href: '/staff/appraisals',
                roles: ['admin'],
                feature: 'Teacher Evaluations',
            },
            {
                id: 'salary-templates',
                label: 'Set Salary',
                icon: Banknote,
                href: '/staff/salary-templates',
                roles: ['admin'],
                feature: 'Payroll Management',
            },
            {
                id: 'recruitment',
                label: 'Recruitment & Hiring',
                icon: UserPlus,
                href: '/recruitment',
                roles: ['admin'],
                feature: 'Recruitment & Hiring',
            },
            {
                id: 'staff-directory',
                label: 'Staff Directory',
                icon: Contact,
                href: '/staff-directory',
                roles: ['admin'],
                feature: 'User Management',
            },
        ],
    },
    {
        id: 'academics',
        label: 'Academics',
        icon: School,
        navMode: 'href-or-id',
        tabs: [
            'academic-dashboard',
            'classes',
            'sections',
            'class-time-table',
            'auto-timetable',
            'teacher-time-table',
            'lesson-plan-dashboard',
            'lesson-plan',
            'homework',
            'subjects',
            'promote-students',
            'report-card-setups',
            'cocurricular',
            'chapters-topics',
            'assign-class-teacher',
            'assign-electives',
            'time-slots',
            'sessions',
        ],
        items: [
            {
                id: 'academic-dashboard',
                label: 'Academic Dashboard',
                icon: School,
                href: '/academics/dashboard',
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Class / Section',
            },
            {
                id: 'classes',
                label: 'Class / Section',
                icon: School,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Class / Section',
            },
            {
                id: 'sections',
                label: 'Sections',
                icon: LayoutList,
                href: '/sections',
                roles: ['super_admin', 'admin'],
                feature: 'Class / Section',
            },
            {
                id: 'class-time-table',
                label: 'Class Time Table',
                icon: Clock3,
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Class Time Table',
            },
            {
                id: 'auto-timetable',
                label: 'Auto Timetable',
                icon: Wand2,
                href: '/auto-timetable',
                roles: ['super_admin', 'admin'],
                feature: 'Auto Timetable',
            },
            {
                id: 'teacher-time-table',
                label: 'Teachers Time Table',
                icon: Clock3,
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Teachers Time Table',
            },
            {
                id: 'lesson-plan-dashboard',
                label: 'Lesson Planner Dashboard',
                icon: BookOpen,
                href: '/lesson-plans/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Lesson Plan',
            },
            {
                id: 'lesson-plan',
                label: 'Lesson Plan',
                icon: BookOpen,
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Lesson Plan',
            },
            {
                id: 'homework',
                label: 'Homework',
                icon: ClipboardPenLine,
                href: '/homework',
                roles: ['super_admin', 'admin', 'teacher', 'student'],
                feature: 'Homework',
            },
            {
                id: 'subjects',
                label: 'Subjects',
                icon: BookOpen,
                roles: ['admin', 'teacher'],
                feature: 'Subjects',
            },
            {
                id: 'promote-students',
                label: 'Promote Students',
                icon: ArrowUpCircle,
                roles: ['admin'],
                feature: 'Promote Students',
            },
            {
                id: 'report-card-setups',
                label: 'Report Card Setups',
                icon: LayoutTemplate,
                href: '/report-card-setups',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Report Card Setups',
                module: 'report-cards',
            },
            {
                id: 'cocurricular',
                label: 'Co-Curricular',
                icon: Award,
                href: '/cocurricular',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Assessment',
            },
            {
                id: 'chapters-topics',
                label: 'Chapters & Topics',
                icon: FolderTree,
                href: '/chapters-topics',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'assign-class-teacher',
                label: 'Assign Class Teacher',
                icon: UserCog,
                href: '/assign-class-teacher',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'assign-electives',
                label: 'Assign Electives',
                icon: BookOpen,
                href: '/assign-electives',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'time-slots',
                label: 'Manage Periods',
                icon: Clock,
                href: '/time-slots',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Exam Management',
            },
            {
                id: 'sessions',
                label: 'Academic Sessions',
                icon: CalendarCheck,
                href: '/sessions',
                roles: ['admin'],
                feature: 'Sessions',
            },
        ],
    },
    {
        id: 'assessment',
        label: 'Assessment',
        icon: ClipboardList,
        navMode: 'href-or-id',
        tabs: ['assessment-dashboard', 'assessment', 'digital-evaluation', 'teacher-evaluations'],
        items: [
            {
                id: 'assessment-dashboard',
                label: 'Assessment Dashboard',
                icon: ClipboardList,
                href: '/assessment/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Assessment',
            },
            {
                id: 'assessment',
                label: 'Assessment',
                icon: ListChecks,
                href: '/assessment',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Assessment',
                module: 'assessment',
            },
            {
                id: 'digital-evaluation',
                label: 'Digital Evaluation',
                icon: ScanText,
                href: '/digital-evaluation',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Digital Evaluation',
                module: 'digital-evaluation',
            },
            {
                id: 'teacher-evaluations',
                label: 'Teacher Evaluations',
                icon: ClipboardList,
                href: '/teacher-evaluations',
                roles: ['admin'],
                feature: 'Teacher Evaluations',
            },
        ],
    },
    {
        id: 'cbc-academics',
        label: 'CBC Academics',
        icon: BookMarked,
        navMode: 'href-or-id',
        tabs: ['cbc-dashboard', 'cbc'],
        items: [
            {
                id: 'cbc-dashboard',
                label: 'CBC Dashboard',
                icon: Layers,
                href: '/cbc/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'CBC',
                module: 'cbc',
            },
            {
                id: 'cbc',
                label: 'CBC',
                icon: Shapes,
                href: '/cbc',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'CBC',
                module: 'cbc',
            },
        ],
    },
    {
        id: 'osm',
        label: 'OSM Module',
        icon: Network,
        navMode: 'href-or-id',
        tabs: ['osm-dashboard', 'osm'],
        items: [
            {
                id: 'osm-dashboard',
                label: 'OSM Dashboard',
                icon: Building2,
                href: '/osm/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Assessment',
            },
            {
                id: 'osm',
                label: 'OSM',
                icon: ClipboardList,
                href: '/osm',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Assessment',
            },
        ],
    },
    {
        id: 'lead-management',
        label: 'Lead Management',
        icon: Target,
        navMode: 'href-or-id',
        tabs: ['lead-dashboard', 'leads'],
        items: [
            {
                id: 'lead-dashboard',
                label: 'Lead Dashboard',
                icon: Inbox,
                href: '/leads/dashboard',
                roles: ['admin', 'receptionist'],
                feature: 'Admission Leads',
            },
            {
                id: 'leads',
                label: 'Leads',
                icon: Target,
                roles: ['admin', 'receptionist'],
                feature: 'Admission Leads',
            },
            {
                id: 'lead-sources-stages',
                label: 'Lead Sources & Stages',
                icon: GitBranch,
                href: '/leads/sources-stages',
                roles: ['super_admin', 'admin'],
                feature: 'Admission Leads',
            },
        ],
    },
    {
        id: 'hpc',
        label: 'Holistic Progress Card',
        icon: BadgeCheck,
        navMode: 'href-or-id',
        tabs: ['hpc-dashboard', 'hpc-activities', 'hpc-cards', 'hpc-frameworks', 'hpc-card-appearance'],
        items: [
            {
                id: 'hpc-dashboard',
                label: 'HPC Dashboard',
                icon: Gauge,
                href: '/hpc/dashboard',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'HPC Progress Cards',
            },
            {
                id: 'hpc-activities',
                label: 'HPC Activities',
                icon: ClipboardList,
                href: '/hpc/activities',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'HPC Progress Cards',
            },
            {
                id: 'hpc-cards',
                label: 'Progress Cards',
                icon: LayoutTemplate,
                href: '/hpc/cards',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'HPC Progress Cards',
            },
            {
                id: 'hpc-frameworks',
                label: 'HPC Frameworks',
                icon: Layers,
                href: '/hpc/frameworks',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'HPC Progress Cards',
            },
            {
                id: 'hpc-card-appearance',
                label: 'Card Appearance',
                icon: Palette,
                href: '/hpc/card-appearance',
                roles: ['super_admin', 'admin'],
                feature: 'HPC Progress Cards',
            },
        ],
    },
    {
        id: 'certificates',
        label: 'Certificates',
        icon: Award,
        navMode: 'href-or-id',
        tabs: ['certificate', 'student-certificates', 'marksheet', 'marksheet-upload', 'generate-document'],
        items: [
            {
                id: 'certificate',
                label: 'Certificate',
                icon: Award,
                href: '/certificates',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Certificate Management',
            },
            {
                id: 'student-certificates',
                label: 'My Certificates',
                icon: Award,
                href: '/my-certificates',
                roles: ['student'],
                feature: 'Certificate Management',
            },
            {
                id: 'marksheet',
                label: 'Marksheet',
                icon: FileText,
                href: '/certificates/marksheet',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Marksheet Management',
            },
            {
                id: 'marksheet-upload',
                label: 'Marksheet Upload',
                icon: Upload,
                href: '/marksheet/upload-list',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Marksheet Management',
            },
            {
                id: 'generate-document',
                label: 'Generate Documents',
                icon: Printer,
                href: '/documents/generate',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Certificate Management',
            },
        ],
    },
    {
        id: 'id-cards',
        label: 'ID Cards',
        icon: IdCard,
        navMode: 'href-or-id',
        tabs: ['student-id-card', 'staff-id-cards'],
        items: [
            {
                id: 'student-id-card',
                label: 'Student ID Card',
                icon: UserRound,
                href: '/certificates/student-id-card',
                roles: ['super_admin', 'admin', 'teacher'],
                feature: 'Student ID Card Management',
            },
            {
                id: 'staff-id-cards',
                label: 'Staff ID Cards',
                icon: CreditCard,
                href: '/staff/id-cards',
                roles: ['admin'],
                feature: 'Staff ID Cards',
            },
        ],
    },
    {
        id: 'comms-wallet',
        label: 'Comms Wallet',
        icon: Wallet,
        navMode: 'href-or-id',
        tabs: ['comms-wallet'],
        items: [
            {
                id: 'comms-wallet',
                label: 'Comms Wallet',
                icon: Wallet,
                href: '/comms-wallet',
                roles: ['admin'],
                feature: 'Messages',
            },
        ],
    },
    {
        id: 'cctv',
        label: 'CCTV',
        icon: Camera,
        navMode: 'href-or-id',
        tabs: ['cctv'],
        items: [
            {
                id: 'cctv',
                label: 'CCTV',
                icon: Video,
                href: '/cctv',
                roles: ['admin'],
                feature: 'Biometric Settings',
            },
        ],
    },
    {
        id: 'school-website',
        label: 'School Website',
        icon: Globe,
        navMode: 'href-or-id',
        tabs: ['facilities', 'website-cms', 'pages-builder', 'cbse-disclosure'],
        items: [
            {
                id: 'facilities',
                label: 'Facilities',
                icon: Building2,
                href: '/facilities',
                roles: ['admin'],
                feature: 'Inventory Management',
            },
            {
                id: 'website-cms',
                label: 'CMS Editor',
                icon: Globe,
                href: '/website-cms',
                roles: ['admin'],
                feature: 'Website CMS',
            },
            {
                id: 'pages-builder',
                label: 'Pages',
                icon: FileText,
                href: '/pages-builder',
                roles: ['admin'],
                feature: 'Website Pages',
            },
            {
                id: 'cbse-disclosure',
                label: 'CBSE Disclosure',
                icon: BookOpenCheck,
                href: '/website-cms/cbse-disclosure',
                roles: ['admin'],
                feature: 'Website CMS',
            },
        ],
    },
    {
        id: 'transport',
        label: 'Transport',
        icon: BusFront,
        navMode: 'href-or-id',
        tabs: ['transport-dashboard', 'transport-management', 'transport-fee-collection'],
        items: [
            {
                id: 'transport-dashboard',
                label: 'Transport Dashboard',
                icon: BusFront,
                href: '/transport/dashboard',
                roles: ['admin', 'receptionist', 'driver'],
                feature: 'Transport Management',
            },
            {
                id: 'transport-management',
                label: 'Transport Management',
                icon: BusFront,
                href: '/transport-management',
                roles: ['admin', 'receptionist', 'driver'],
                feature: 'Transport Management',
            },
            {
                id: 'transport-fee-collection',
                label: 'Fee Collection',
                icon: IndianRupee,
                href: '/transport-fee-collection',
                roles: ['admin', 'receptionist'],
                feature: 'Transport Fee Collection',
            },
        ],
    },
    {
        id: 'biometric',
        label: 'Biometric Devices',
        icon: Fingerprint,
        navMode: 'href-or-id',
        tabs: ['biometric-settings', 'biometric-devices', 'agent-logs'],
        items: [
            {
                id: 'biometric-settings',
                label: 'Biometric Settings',
                icon: Fingerprint,
                href: '/settings/biometric',
                roles: ['super_admin', 'admin'],
                feature: 'Biometric Settings',
            },
            {
                id: 'biometric-devices',
                label: 'Biometric Devices',
                icon: ScanFace,
                href: '/biometric-devices',
                roles: ['super_admin', 'admin'],
                feature: 'Biometric Settings',
            },
            {
                id: 'agent-logs',
                label: 'Agent Logs',
                icon: History,
                href: '/agent-logs',
                roles: ['super_admin', 'admin'],
                feature: 'Biometric Settings',
            },
        ],
    },
    {
        id: 'reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        navMode: 'href-or-id',
        tabs: [
            'reports-overview',
            'reports-students',
            'reports-attendance',
            'reports-fees',
            'reports-exams',
            'reports-library',
            'reports-transport',
            'reports-hostel',
            'reports-inventory',
            'reports-front-office',
            'reports-communication',
            'reports-lesson-plan',
            'reports-human-resource',
            'reports-homework',
            'reports-alumni',
            'reports-activity-log',
            'reports-audit-trail',
            'regulator-reports',
            'qr-scan-audit',
        ],
        items: [
            {
                id: 'reports-overview',
                label: 'Overview Dashboard',
                icon: BarChart3,
                href: '/reports',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-students',
                label: 'Students',
                icon: Users,
                href: '/reports?module=students',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-attendance',
                label: 'Attendance',
                icon: CalendarCheck,
                href: '/reports?module=attendance',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-fees',
                label: 'Fees',
                icon: IndianRupee,
                href: '/reports?module=fees',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-exams',
                label: 'Exams',
                icon: FileText,
                href: '/reports?module=exams',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-library',
                label: 'Library',
                icon: Book,
                href: '/reports?module=library',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-transport',
                label: 'Transport',
                icon: BusFront,
                href: '/reports?module=transport',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-hostel',
                label: 'Hostel',
                icon: BedDouble,
                href: '/reports?module=hostel',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-inventory',
                label: 'Inventory',
                icon: Boxes,
                href: '/reports?module=inventory',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-front-office',
                label: 'Front Office',
                icon: Briefcase,
                href: '/reports?module=front-office',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-communication',
                label: 'Communication',
                icon: MessageSquare,
                href: '/reports?module=communication',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-lesson-plan',
                label: 'Lesson Plan',
                icon: BookOpen,
                href: '/reports?module=lesson-plan',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-human-resource',
                label: 'Human Resource',
                icon: UserCog,
                href: '/reports?module=human-resource',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-homework',
                label: 'Homework',
                icon: ClipboardPenLine,
                href: '/reports?module=homework',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-alumni',
                label: 'Alumni',
                icon: GraduationCap,
                href: '/reports?module=alumni',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-activity-log',
                label: 'Activity Log',
                icon: ClipboardList,
                href: '/reports?module=activity-log',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'reports-audit-trail',
                label: 'Audit Trail',
                icon: ShieldCheck,
                href: '/audit-trail',
                roles: ['super_admin', 'admin'],
                feature: 'Audit Trail',
                module: 'audit-trail',
            },
            {
                id: 'regulator-reports',
                label: 'Regulator Reports',
                icon: FileClock,
                href: '/regulator-reports',
                roles: ['super_admin', 'admin'],
                feature: 'Reports & Analytics',
            },
            {
                id: 'qr-scan-audit',
                label: 'QR Scan Audit',
                icon: QrCode,
                href: '/qr-scan-audit',
                roles: ['super_admin', 'admin'],
                feature: 'QR Code Attendance',
            },
        ],
    },
];
