<?php

namespace App\Support;

class RolePermissionCatalog
{
    public static function features(): array
    {
        return [
            ['module' => 'Dashboard', 'feature' => 'Dashboard Home'],
            ['module' => 'Students', 'feature' => 'Search Students'],
            ['module' => 'Students', 'feature' => 'Student Details'],
            ['module' => 'Students', 'feature' => 'Edit Student'],
            ['module' => 'Students', 'feature' => 'Online Admission'],
            ['module' => 'Students', 'feature' => 'Bulk Delete Students'],
            ['module' => 'Students', 'feature' => 'Alumni Records'],
            ['module' => 'Staff', 'feature' => 'User Management'],
            ['module' => 'Staff', 'feature' => 'Staff Attendance'],
            ['module' => 'Staff', 'feature' => 'Payroll Management'],
            ['module' => 'Staff', 'feature' => 'Leave Management'],
            ['module' => 'Staff', 'feature' => 'Teacher Evaluations'],
            ['module' => 'Staff', 'feature' => 'Staff ID Cards'],
            ['module' => 'Staff', 'feature' => 'Recruitment & Hiring'],
            ['module' => 'Inventory', 'feature' => 'Vendors & Purchase Orders'],
            ['module' => 'Academics', 'feature' => 'Class / Section'],
            ['module' => 'Academics', 'feature' => 'Class Time Table'],
            ['module' => 'Academics', 'feature' => 'Auto Timetable'],
            ['module' => 'Academics', 'feature' => 'Teachers Time Table'],
            ['module' => 'Academics', 'feature' => 'Lesson Plan'],
            ['module' => 'Academics', 'feature' => 'Homework'],
            ['module' => 'Academics', 'feature' => 'Study Materials'],
            ['module' => 'Academics', 'feature' => 'Question Bank'],
            ['module' => 'Academics', 'feature' => 'Live Online Classes'],
            ['module' => 'Academics', 'feature' => 'Syllabus Coverage'],
            ['module' => 'Academics', 'feature' => 'Todo'],
            ['module' => 'Academics', 'feature' => 'Subjects'],
            ['module' => 'Academics', 'feature' => 'Promote Students'],
            ['module' => 'Front Office', 'feature' => 'Admission Enquiry'],
            ['module' => 'Front Office', 'feature' => 'Admission Leads'],
            ['module' => 'Front Office', 'feature' => 'Visitor Register'],
            ['module' => 'Front Office', 'feature' => 'Phone Call Log'],
            ['module' => 'Front Office', 'feature' => 'Postal Dispatch'],
            ['module' => 'Front Office', 'feature' => 'Postal Delivery'],
            ['module' => 'Front Office', 'feature' => 'Complains'],
            ['module' => 'Front Office', 'feature' => 'Parent Helpdesk'],
            ['module' => 'Communication', 'feature' => 'Live Chat'],
            ['module' => 'Fees', 'feature' => 'Fees Management'],
            ['module' => 'Fees', 'feature' => 'Scholarship & Discounts'],
            ['module' => 'Fees', 'feature' => 'Tally Export'],
            ['module' => 'Fees', 'feature' => 'Income Management'],
            ['module' => 'Fees', 'feature' => 'Expense Management'],
            ['module' => 'Fees', 'feature' => 'Bank Accounts'],
            ['module' => 'Hostel', 'feature' => 'Hostel Management'],
            ['module' => 'Hostel', 'feature' => 'Hostel Fee Collection'],
            ['module' => 'Hostel', 'feature' => 'Hostel Complaints'],
            ['module' => 'Hostel', 'feature' => 'Hostel Notice Board'],
            ['module' => 'Hostel', 'feature' => 'Hostel Lost & Found'],
            ['module' => 'Attendance', 'feature' => 'Attendance Management'],
            ['module' => 'Attendance', 'feature' => 'QR Code Attendance'],
            ['module' => 'Exams', 'feature' => 'Exam Management'],
            ['module' => 'Exams', 'feature' => 'Hall Ticket'],
            ['module' => 'Exams', 'feature' => 'Print Marksheet'],
            ['module' => 'Exams', 'feature' => 'Report Card'],
            ['module' => 'Exams', 'feature' => 'HPC Progress Cards'],
            ['module' => 'Exams', 'feature' => 'Online Exams'],
            ['module' => 'Communication', 'feature' => 'Feedback Management'],
            ['module' => 'Certificates', 'feature' => 'Certificate Management'],
            ['module' => 'Certificates', 'feature' => 'Marksheet Management'],
            ['module' => 'Certificates', 'feature' => 'Student ID Card Management'],
            ['module' => 'Library', 'feature' => 'Library Management'],
            ['module' => 'Library', 'feature' => 'E-Library'],
            ['module' => 'Inventory', 'feature' => 'Inventory Management'],
            ['module' => 'Communication', 'feature' => 'Messages'],
            ['module' => 'Communication', 'feature' => 'Send Whatsapp'],
            ['module' => 'Communication', 'feature' => 'Send QWA Whatsapp'],
            ['module' => 'Communication', 'feature' => 'Notice Board'],
            ['module' => 'Communication', 'feature' => 'Voice Calls'],
            ['module' => 'Communication', 'feature' => 'Send Emails'],
            ['module' => 'Communication', 'feature' => 'Send SMS'],
            ['module' => 'Communication', 'feature' => 'Image Gallery'],
            ['module' => 'Communication', 'feature' => 'Download Center'],
            ['module' => 'Transport', 'feature' => 'Transport Management'],
            ['module' => 'Transport', 'feature' => 'Transport Fee Collection'],
            ['module' => 'Events', 'feature' => 'Events Calendar'],
            ['module' => 'Student Information', 'feature' => 'Discipline'],
            ['module' => 'Student Information', 'feature' => 'Student Health'],
            ['module' => 'Student Information', 'feature' => 'PTM'],
            ['module' => 'Student Information', 'feature' => 'TC & Exit'],
            ['module' => 'Reports', 'feature' => 'Reports & Analytics'],
            ['module' => 'Reports', 'feature' => 'Audit Trail'],
            ['module' => 'Assets', 'feature' => 'Asset Management'],
            ['module' => 'Academics', 'feature' => 'Assessment'],
            ['module' => 'Academics', 'feature' => 'Digital Evaluation'],
            ['module' => 'Academics', 'feature' => 'Report Card Setups'],
            ['module' => 'Academics', 'feature' => 'CBC'],
            ['module' => 'AI & Apps', 'feature' => 'Apps Center'],
            ['module' => 'System', 'feature' => 'Branch Admin'],
            ['module' => 'Knowledge Base', 'feature' => 'Knowledge Base'],
            ['module' => 'Settings', 'feature' => 'General Setting'],
            ['module' => 'Settings', 'feature' => 'Subscription Management'],
            ['module' => 'Settings', 'feature' => 'Content Safety'],
            ['module' => 'Settings', 'feature' => 'Communication Setting'],
            ['module' => 'Settings', 'feature' => 'Online Payment Setting'],
            ['module' => 'Settings', 'feature' => 'Roles & Permissions'],
            ['module' => 'Settings', 'feature' => 'Sessions'],
            ['module' => 'Settings', 'feature' => 'SSO Settings'],
            ['module' => 'Settings', 'feature' => 'Biometric Settings'],
            ['module' => 'Settings', 'feature' => 'Module Management'],
            ['module' => 'Settings', 'feature' => 'AI Assistant'],
            ['module' => 'Website', 'feature' => 'Website CMS'],
            ['module' => 'Website', 'feature' => 'Website Pages'],
            ['module' => 'Account', 'feature' => 'Profile'],
            ['module' => 'Account', 'feature' => 'Edit Profile'],
            ['module' => 'Account', 'feature' => 'My Leaves'],
        ];
    }

    public static function staffRoles(): array
    {
        return [
            'admin' => 'Admin',
            'teacher' => 'Teacher',
            'receptionist' => 'Receptionist',
            'accountant' => 'Accountant',
            'librarian' => 'Librarian',
            'driver' => 'Driver',
        ];
    }

    public static function staffRoleSlugs(): array
    {
        return array_keys(self::staffRoles());
    }

    public static function staffRoleNames(): array
    {
        return array_values(self::staffRoles());
    }

    public static function displayNameForSlug(string $slug): ?string
    {
        return self::staffRoles()[$slug] ?? null;
    }

    public static function slugForDisplayName(string $name): ?string
    {
        $slug = array_search($name, self::staffRoles(), true);

        return $slug === false ? null : $slug;
    }

    public static function featureMap(): array
    {
        return collect(self::features())
            ->keyBy('feature')
            ->all();
    }

    public static function defaultViewForRole(string $slug, string $feature): bool
    {
        $name = self::staffRoles()[$slug] ?? null;

        if (! $name) {
            return false;
        }

        $defaults = self::defaults();

        return (bool) ($defaults[$name][$feature]['view'] ?? false);
    }

    public static function emptyPermissions(): array
    {
        return collect(self::features())->mapWithKeys(fn (array $item) => [
            $item['feature'] => [
                'view' => false,
                'add' => false,
                'edit' => false,
                'delete' => false,
            ],
        ])->all();
    }

    public static function defaults(): array
    {
        return [
            'Admin' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Search Students' => self::featurePermissions(true, true, true, true),
                'Student Details' => self::featurePermissions(true),
                'Edit Student' => self::featurePermissions(true, false, true),
                'Online Admission' => self::featurePermissions(true, true, true, true),
                'Bulk Delete Students' => self::featurePermissions(true, false, false, true),
                'Alumni Records' => self::featurePermissions(true, true, true, true),
                'User Management' => self::featurePermissions(true, true, true, true),
                'Staff Attendance' => self::featurePermissions(true, true, true, true),
                'Payroll Management' => self::featurePermissions(true, true, true, true),
                'Leave Management' => self::featurePermissions(true, true, true, true),
                'Teacher Evaluations' => self::featurePermissions(true, true, true, true),
                'Staff ID Cards' => self::featurePermissions(true, true, true, true),
                'Recruitment & Hiring' => self::featurePermissions(true, true, true, true),
                'Class / Section' => self::featurePermissions(true, true, true, true),
                'Class Time Table' => self::featurePermissions(true, true, true, true),
                'Auto Timetable' => self::featurePermissions(true, true, true, true),
                'Teachers Time Table' => self::featurePermissions(true, true, true, true),
                'Lesson Plan' => self::featurePermissions(true, true, true, true),
                'Homework' => self::featurePermissions(true, true, true, true),
                'Study Materials' => self::featurePermissions(true, true, true, true),
                'Question Bank' => self::featurePermissions(true, true, true, true),
                'Live Online Classes' => self::featurePermissions(true, true, true, true),
                'Syllabus Coverage' => self::featurePermissions(true, true, true, true),
                'Todo' => self::featurePermissions(true, true, true, true),
                'Subjects' => self::featurePermissions(true, true, true, true),
                'Promote Students' => self::featurePermissions(true, true, true),
                'Admission Enquiry' => self::featurePermissions(true, true, true, true),
                'Admission Leads' => self::featurePermissions(true, true, true, true),
                'Visitor Register' => self::featurePermissions(true, true, true, true),
                'Phone Call Log' => self::featurePermissions(true, true, true, true),
                'Postal Dispatch' => self::featurePermissions(true, true, true, true),
                'Postal Delivery' => self::featurePermissions(true, true, true, true),
                'Complains' => self::featurePermissions(true, true, true, true),
                'Parent Helpdesk' => self::featurePermissions(true, true, true, true),
                'Live Chat' => self::featurePermissions(true, true, true, true),
                'Fees Management' => self::featurePermissions(true, true, true, true),
                'Scholarship & Discounts' => self::featurePermissions(true, true, true, true),
                'Tally Export' => self::featurePermissions(true),
                'Income Management' => self::featurePermissions(true, true, true, true),
                'Expense Management' => self::featurePermissions(true, true, true, true),
                'Bank Accounts' => self::featurePermissions(true, true, true, true),
                'Hostel Management' => self::featurePermissions(true, true, true, true),
                'Hostel Fee Collection' => self::featurePermissions(true, true, true, true),
                'Hostel Complaints' => self::featurePermissions(true, true, true, true),
                'Hostel Notice Board' => self::featurePermissions(true, true, true, true),
                'Hostel Lost & Found' => self::featurePermissions(true, true, true, true),
                'Attendance Management' => self::featurePermissions(true, true, true, true),
                'QR Code Attendance' => self::featurePermissions(true, true, true, true),
                'Exam Management' => self::featurePermissions(true, true, true, true),
                'Hall Ticket' => self::featurePermissions(true, true, true, true),
                'Print Marksheet' => self::featurePermissions(true, true, true, true),
                'Report Card' => self::featurePermissions(true, true, true, true),
                'HPC Progress Cards' => self::featurePermissions(true, true, true, true),
                'Online Exams' => self::featurePermissions(true, true, true, true),
                'Feedback Management' => self::featurePermissions(true, true, true, true),
                'Certificate Management' => self::featurePermissions(true, true, true, true),
                'Marksheet Management' => self::featurePermissions(true, true, true, true),
                'Student ID Card Management' => self::featurePermissions(true, true, true, true),
                'Library Management' => self::featurePermissions(true, true, true, true),
                'E-Library' => self::featurePermissions(true, true, true, true),
                'Inventory Management' => self::featurePermissions(true, true, true, true),
                'Vendors & Purchase Orders' => self::featurePermissions(true, true, true, true),
                'Messages' => self::featurePermissions(true, true, true, true),
                'Send Whatsapp' => self::featurePermissions(true, true, true, true),
                'Send QWA Whatsapp' => self::featurePermissions(true, true, true, true),
                'Notice Board' => self::featurePermissions(true, true, true, true),
                'Voice Calls' => self::featurePermissions(true, true, true, true),
                'Send Emails' => self::featurePermissions(true, true, true, true),
                'Send SMS' => self::featurePermissions(true, true, true, true),
                'Download Center' => self::featurePermissions(true, true, true, true),
                'Image Gallery' => self::featurePermissions(true, true, true, true),
                'Transport Management' => self::featurePermissions(true, true, true, true),
                'Transport Fee Collection' => self::featurePermissions(true, true, true, true),
                'Events Calendar' => self::featurePermissions(true, true, true, true),
                'Discipline' => self::featurePermissions(true, true, true, true),
                'Student Health' => self::featurePermissions(true, true, true, true),
                'PTM' => self::featurePermissions(true, true, true, true),
                'TC & Exit' => self::featurePermissions(true, true, true, true),
                'Reports & Analytics' => self::featurePermissions(true),
                'Audit Trail' => self::featurePermissions(true),
                'Asset Management' => self::featurePermissions(true, true, true, true),
                'Assessment' => self::featurePermissions(true, true, true, true),
                'Digital Evaluation' => self::featurePermissions(true, true, true, true),
                'Report Card Setups' => self::featurePermissions(true, true, true, true),
                'CBC' => self::featurePermissions(true, true, true, true),
                'Apps Center' => self::featurePermissions(true, true),
                'Knowledge Base' => self::featurePermissions(true),
                'General Setting' => self::featurePermissions(true, false, true),
                'Subscription Management' => self::featurePermissions(true),
                'Content Safety' => self::featurePermissions(true, true, true, true),
                'Communication Setting' => self::featurePermissions(true, false, true),
                'Online Payment Setting' => self::featurePermissions(true, false, true),
                'Roles & Permissions' => self::featurePermissions(true, false, true),
                'Sessions' => self::featurePermissions(true, true, true, true),
                'SSO Settings' => self::featurePermissions(true, false, true),
                'Biometric Settings' => self::featurePermissions(true, false, true),
                'AI Assistant' => self::featurePermissions(true, false, true),
                'Module Management' => self::featurePermissions(true, false, true),
                'Website CMS' => self::featurePermissions(true, true, true, true),
                'Website Pages' => self::featurePermissions(true, true, true, true),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true, true),
            ],
            'Teacher' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Search Students' => self::featurePermissions(true, false, true),
                'Student Details' => self::featurePermissions(true),
                'Edit Student' => self::featurePermissions(false),
                'Online Admission' => self::featurePermissions(true, true),
                'Bulk Delete Students' => self::featurePermissions(false),
                'Alumni Records' => self::featurePermissions(true),
                'User Management' => self::featurePermissions(false),
                'Staff Attendance' => self::featurePermissions(false),
                'Payroll Management' => self::featurePermissions(false),
                'Leave Management' => self::featurePermissions(false),
                'Class / Section' => self::featurePermissions(true),
                'Class Time Table' => self::featurePermissions(true),
                'Teachers Time Table' => self::featurePermissions(true),
                'Lesson Plan' => self::featurePermissions(true, true, true, true),
                'Homework' => self::featurePermissions(true, true, true),
                'Study Materials' => self::featurePermissions(true, true, true, true),
                'Question Bank' => self::featurePermissions(true, true, true, true),
                'Live Online Classes' => self::featurePermissions(true, true, true, true),
                'Syllabus Coverage' => self::featurePermissions(true, true, true, true),
                'Todo' => self::featurePermissions(true, true, true, true),
                'Subjects' => self::featurePermissions(true, true, true),
                'Promote Students' => self::featurePermissions(false),
                'Admission Enquiry' => self::featurePermissions(false),
                'Admission Leads' => self::featurePermissions(true, false, false, false),
                'Visitor Register' => self::featurePermissions(false),
                'Phone Call Log' => self::featurePermissions(false),
                'Postal Dispatch' => self::featurePermissions(false),
                'Postal Delivery' => self::featurePermissions(false),
                'Complains' => self::featurePermissions(false),
                'Parent Helpdesk' => self::featurePermissions(true, true, true),
                'Live Chat' => self::featurePermissions(true, true, true),
                'Fees Management' => self::featurePermissions(false),
                'Income Management' => self::featurePermissions(false),
                'Expense Management' => self::featurePermissions(false),
                'Bank Accounts' => self::featurePermissions(false),
                'Hostel Management' => self::featurePermissions(false),
                'Hostel Fee Collection' => self::featurePermissions(false),
                'Hostel Complaints' => self::featurePermissions(false),
                'Hostel Notice Board' => self::featurePermissions(false),
                'Hostel Lost & Found' => self::featurePermissions(false),
                'Attendance Management' => self::featurePermissions(true, true, true),
                'QR Code Attendance' => self::featurePermissions(true, true, true),
                'Exam Management' => self::featurePermissions(true, true, true),
                'Hall Ticket' => self::featurePermissions(true),
                'Print Marksheet' => self::featurePermissions(true),
                'Report Card' => self::featurePermissions(true, true),
                'HPC Progress Cards' => self::featurePermissions(true, true),
                'Online Exams' => self::featurePermissions(true, true, true),
                'Assessment' => self::featurePermissions(true, true, true, true),
                'Digital Evaluation' => self::featurePermissions(true, true, true, true),
                'Report Card Setups' => self::featurePermissions(true),
                'CBC' => self::featurePermissions(true, true, true, true),
                'Feedback Management' => self::featurePermissions(true, true, false, false),
                'Certificate Management' => self::featurePermissions(true, true, true),
                'Marksheet Management' => self::featurePermissions(true, true, true),
                'Student ID Card Management' => self::featurePermissions(true, true, true),
                'Library Management' => self::featurePermissions(true),
                'E-Library' => self::featurePermissions(true, true, true),
                'Inventory Management' => self::featurePermissions(false),
                'Messages' => self::featurePermissions(true, true, true),
                'Send Whatsapp' => self::featurePermissions(true, true, true),
                'Notice Board' => self::featurePermissions(true, true, true),
                'Voice Calls' => self::featurePermissions(true, true),
                'Send Emails' => self::featurePermissions(true, true),
                'Send SMS' => self::featurePermissions(true, true),
                'Download Center' => self::featurePermissions(true, true, true),
                'Image Gallery' => self::featurePermissions(true, true, true),
                'Transport Management' => self::featurePermissions(false),
                'Transport Fee Collection' => self::featurePermissions(false),
                'Events Calendar' => self::featurePermissions(true, true, true),
                'Discipline' => self::featurePermissions(true, true, true),
                'Student Health' => self::featurePermissions(true, true, true),
                'PTM' => self::featurePermissions(true, true, true),
                'TC & Exit' => self::featurePermissions(false),
                'Reports & Analytics' => self::featurePermissions(false),
                'Knowledge Base' => self::featurePermissions(false),
                'General Setting' => self::featurePermissions(false),
                'Subscription Management' => self::featurePermissions(false),
                'Content Safety' => self::featurePermissions(false),
                'Communication Setting' => self::featurePermissions(false),
                'Online Payment Setting' => self::featurePermissions(false),
                'Roles & Permissions' => self::featurePermissions(false),
                'Sessions' => self::featurePermissions(false),
                'Website CMS' => self::featurePermissions(false),
                'Website Pages' => self::featurePermissions(false),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true, true),
            ],
            'Receptionist' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Search Students' => self::featurePermissions(true, true),
                'Student Details' => self::featurePermissions(true),
                'Edit Student' => self::featurePermissions(false),
                'Online Admission' => self::featurePermissions(true, true, true),
                'Bulk Delete Students' => self::featurePermissions(false),
                'Alumni Records' => self::featurePermissions(true, true),
                'User Management' => self::featurePermissions(false),
                'Staff Attendance' => self::featurePermissions(false),
                'Payroll Management' => self::featurePermissions(false),
                'Leave Management' => self::featurePermissions(false),
                'Class / Section' => self::featurePermissions(false),
                'Class Time Table' => self::featurePermissions(true),
                'Teachers Time Table' => self::featurePermissions(true),
                'Lesson Plan' => self::featurePermissions(false),
                'Homework' => self::featurePermissions(false),
                'Todo' => self::featurePermissions(true, true, true, true),
                'Subjects' => self::featurePermissions(false),
                'Promote Students' => self::featurePermissions(false),
                'Admission Enquiry' => self::featurePermissions(true, true, true, true),
                'Admission Leads' => self::featurePermissions(true, true, true, true),
                'Visitor Register' => self::featurePermissions(true, true, true, true),
                'Phone Call Log' => self::featurePermissions(true, true, true, true),
                'Postal Dispatch' => self::featurePermissions(true, true, true, true),
                'Postal Delivery' => self::featurePermissions(true, true, true, true),
                'Complains' => self::featurePermissions(true, true, true, true),
                'Parent Helpdesk' => self::featurePermissions(true, true, true, true),
                'Live Chat' => self::featurePermissions(true, true, true, true),
                'Fees Management' => self::featurePermissions(true, true),
                'Income Management' => self::featurePermissions(false),
                'Expense Management' => self::featurePermissions(false),
                'Bank Accounts' => self::featurePermissions(true, true),
                'Bank Accounts' => self::featurePermissions(false),
                'Hostel Management' => self::featurePermissions(false),
                'Hostel Fee Collection' => self::featurePermissions(false),
                'Hostel Complaints' => self::featurePermissions(false),
                'Hostel Notice Board' => self::featurePermissions(false),
                'Hostel Lost & Found' => self::featurePermissions(false),
                'Attendance Management' => self::featurePermissions(false),
                'Exam Management' => self::featurePermissions(false),
                'Hall Ticket' => self::featurePermissions(false),
                'Print Marksheet' => self::featurePermissions(false),
                'Report Card' => self::featurePermissions(false),
                'HPC Progress Cards' => self::featurePermissions(false),
                'Online Exams' => self::featurePermissions(false),
                'Feedback Management' => self::featurePermissions(false),
                'Certificate Management' => self::featurePermissions(false),
                'Marksheet Management' => self::featurePermissions(false),
                'Student ID Card Management' => self::featurePermissions(false),
                'Library Management' => self::featurePermissions(false),
                'Inventory Management' => self::featurePermissions(true, true, true),
                'Messages' => self::featurePermissions(true, true, true),
                'Send Whatsapp' => self::featurePermissions(true, true, true),
                'Notice Board' => self::featurePermissions(true),
                'Voice Calls' => self::featurePermissions(true, true, true),
                'Send Emails' => self::featurePermissions(true, true),
                'Send SMS' => self::featurePermissions(true, true),
                'Download Center' => self::featurePermissions(true, true, true),
                'Image Gallery' => self::featurePermissions(true, true, true),
                'Transport Management' => self::featurePermissions(true, true, true, true),
                'Transport Fee Collection' => self::featurePermissions(true, true, true, true),
                'Events Calendar' => self::featurePermissions(true, true, true),
                'Discipline' => self::featurePermissions(true, true, true),
                'Student Health' => self::featurePermissions(true, true, true),
                'PTM' => self::featurePermissions(true, true, true),
                'TC & Exit' => self::featurePermissions(false),
                'Reports & Analytics' => self::featurePermissions(false),
                'Knowledge Base' => self::featurePermissions(false),
                'General Setting' => self::featurePermissions(false),
                'Subscription Management' => self::featurePermissions(false),
                'Content Safety' => self::featurePermissions(false),
                'Communication Setting' => self::featurePermissions(false),
                'Online Payment Setting' => self::featurePermissions(false),
                'Roles & Permissions' => self::featurePermissions(false),
                'Sessions' => self::featurePermissions(false),
                'Website CMS' => self::featurePermissions(false),
                'Website Pages' => self::featurePermissions(false),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true, true),
            ],
            'Accountant' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Search Students' => self::featurePermissions(true),
                'Student Details' => self::featurePermissions(true),
                'Edit Student' => self::featurePermissions(false),
                'Online Admission' => self::featurePermissions(false),
                'Bulk Delete Students' => self::featurePermissions(false),
                'Alumni Records' => self::featurePermissions(false),
                'User Management' => self::featurePermissions(false),
                'Staff Attendance' => self::featurePermissions(false),
                'Payroll Management' => self::featurePermissions(false),
                'Leave Management' => self::featurePermissions(false),
                'Class / Section' => self::featurePermissions(false),
                'Class Time Table' => self::featurePermissions(false),
                'Teachers Time Table' => self::featurePermissions(false),
                'Lesson Plan' => self::featurePermissions(false),
                'Homework' => self::featurePermissions(false),
                'Todo' => self::featurePermissions(true, true, true, true),
                'Subjects' => self::featurePermissions(false),
                'Promote Students' => self::featurePermissions(false),
                'Admission Enquiry' => self::featurePermissions(false),
                'Admission Leads' => self::featurePermissions(true, false, false, false),
                'Visitor Register' => self::featurePermissions(false),
                'Phone Call Log' => self::featurePermissions(false),
                'Postal Dispatch' => self::featurePermissions(false),
                'Postal Delivery' => self::featurePermissions(false),
                'Complains' => self::featurePermissions(false),
                'Fees Management' => self::featurePermissions(true, true, true, true),
                'Scholarship & Discounts' => self::featurePermissions(true, true, true, true),
                'Tally Export' => self::featurePermissions(true),
                'Income Management' => self::featurePermissions(true, true, true, true),
                'Expense Management' => self::featurePermissions(true, true, true, true),
                'Bank Accounts' => self::featurePermissions(true, true, true, true),
                'Hostel Management' => self::featurePermissions(false),
                'Hostel Fee Collection' => self::featurePermissions(false),
                'Hostel Complaints' => self::featurePermissions(false),
                'Hostel Notice Board' => self::featurePermissions(false),
                'Hostel Lost & Found' => self::featurePermissions(false),
                'Attendance Management' => self::featurePermissions(false),
                'Exam Management' => self::featurePermissions(false),
                'Hall Ticket' => self::featurePermissions(false),
                'Print Marksheet' => self::featurePermissions(false),
                'Report Card' => self::featurePermissions(false),
                'HPC Progress Cards' => self::featurePermissions(false),
                'Online Exams' => self::featurePermissions(false),
                'Feedback Management' => self::featurePermissions(false),
                'Certificate Management' => self::featurePermissions(false),
                'Marksheet Management' => self::featurePermissions(false),
                'Student ID Card Management' => self::featurePermissions(false),
                'Library Management' => self::featurePermissions(false),
                'Inventory Management' => self::featurePermissions(true, true, true, true),
                'Messages' => self::featurePermissions(false),
                'Send Whatsapp' => self::featurePermissions(false),
                'Send QWA Whatsapp' => self::featurePermissions(false),
                'Notice Board' => self::featurePermissions(false),
                'Voice Calls' => self::featurePermissions(false),
                'Send Emails' => self::featurePermissions(false),
                'Send SMS' => self::featurePermissions(false),
                'Download Center' => self::featurePermissions(false),
                'Transport Management' => self::featurePermissions(false),
                'Transport Fee Collection' => self::featurePermissions(false),
                'Events Calendar' => self::featurePermissions(false),
                'Discipline' => self::featurePermissions(false),
                'Student Health' => self::featurePermissions(false),
                'PTM' => self::featurePermissions(false),
                'TC & Exit' => self::featurePermissions(false),
                'Reports & Analytics' => self::featurePermissions(true),
                'Knowledge Base' => self::featurePermissions(false),
                'General Setting' => self::featurePermissions(false),
                'Subscription Management' => self::featurePermissions(false),
                'Content Safety' => self::featurePermissions(false),
                'Communication Setting' => self::featurePermissions(false),
                'Online Payment Setting' => self::featurePermissions(false),
                'Roles & Permissions' => self::featurePermissions(false),
                'Sessions' => self::featurePermissions(false),
                'Website CMS' => self::featurePermissions(false),
                'Website Pages' => self::featurePermissions(false),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true, true),
            ],
            'Librarian' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Search Students' => self::featurePermissions(true),
                'Student Details' => self::featurePermissions(true),
                'Edit Student' => self::featurePermissions(false),
                'Online Admission' => self::featurePermissions(false),
                'Bulk Delete Students' => self::featurePermissions(false),
                'Alumni Records' => self::featurePermissions(false),
                'User Management' => self::featurePermissions(false),
                'Staff Attendance' => self::featurePermissions(false),
                'Payroll Management' => self::featurePermissions(false),
                'Leave Management' => self::featurePermissions(false),
                'Class / Section' => self::featurePermissions(false),
                'Class Time Table' => self::featurePermissions(false),
                'Teachers Time Table' => self::featurePermissions(false),
                'Lesson Plan' => self::featurePermissions(false),
                'Homework' => self::featurePermissions(false),
                'Todo' => self::featurePermissions(true, true, true, true),
                'Subjects' => self::featurePermissions(false),
                'Promote Students' => self::featurePermissions(false),
                'Admission Enquiry' => self::featurePermissions(false),
                'Admission Leads' => self::featurePermissions(false),
                'Visitor Register' => self::featurePermissions(false),
                'Phone Call Log' => self::featurePermissions(false),
                'Postal Dispatch' => self::featurePermissions(false),
                'Postal Delivery' => self::featurePermissions(false),
                'Complains' => self::featurePermissions(false),
                'Fees Management' => self::featurePermissions(false),
                'Income Management' => self::featurePermissions(false),
                'Expense Management' => self::featurePermissions(false),
                'Bank Accounts' => self::featurePermissions(false),
                'Hostel Management' => self::featurePermissions(false),
                'Hostel Fee Collection' => self::featurePermissions(false),
                'Hostel Complaints' => self::featurePermissions(false),
                'Hostel Notice Board' => self::featurePermissions(false),
                'Hostel Lost & Found' => self::featurePermissions(false),
                'Attendance Management' => self::featurePermissions(false),
                'Exam Management' => self::featurePermissions(false),
                'Hall Ticket' => self::featurePermissions(false),
                'Print Marksheet' => self::featurePermissions(false),
                'Report Card' => self::featurePermissions(false),
                'HPC Progress Cards' => self::featurePermissions(false),
                'Online Exams' => self::featurePermissions(false),
                'Feedback Management' => self::featurePermissions(false),
                'Certificate Management' => self::featurePermissions(false),
                'Marksheet Management' => self::featurePermissions(false),
                'Student ID Card Management' => self::featurePermissions(false),
                'Library Management' => self::featurePermissions(true, true, true, true),
                'E-Library' => self::featurePermissions(true, true, true, true),
                'Inventory Management' => self::featurePermissions(true, true, true, true),
                'Messages' => self::featurePermissions(false),
                'Send Whatsapp' => self::featurePermissions(false),
                'Send QWA Whatsapp' => self::featurePermissions(false),
                'Notice Board' => self::featurePermissions(true),
                'Voice Calls' => self::featurePermissions(false),
                'Send Emails' => self::featurePermissions(false),
                'Send SMS' => self::featurePermissions(false),
                'Download Center' => self::featurePermissions(true),
                'Image Gallery' => self::featurePermissions(true),
                'Transport Management' => self::featurePermissions(false),
                'Transport Fee Collection' => self::featurePermissions(false),
                'Events Calendar' => self::featurePermissions(false),
                'Discipline' => self::featurePermissions(false),
                'Student Health' => self::featurePermissions(false),
                'PTM' => self::featurePermissions(false),
                'TC & Exit' => self::featurePermissions(false),
                'Reports & Analytics' => self::featurePermissions(false),
                'Knowledge Base' => self::featurePermissions(false),
                'General Setting' => self::featurePermissions(false),
                'Subscription Management' => self::featurePermissions(false),
                'Content Safety' => self::featurePermissions(false),
                'Communication Setting' => self::featurePermissions(false),
                'Online Payment Setting' => self::featurePermissions(false),
                'Roles & Permissions' => self::featurePermissions(false),
                'Sessions' => self::featurePermissions(false),
                'Website CMS' => self::featurePermissions(false),
                'Website Pages' => self::featurePermissions(false),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true, true),
            ],
            'Driver' => [
                'Dashboard Home' => self::featurePermissions(true),
                'Transport Management' => self::featurePermissions(true, true, true),
                'Transport Fee Collection' => self::featurePermissions(false),
                'Admission Leads' => self::featurePermissions(false),
                'Events Calendar' => self::featurePermissions(false),
                'Discipline' => self::featurePermissions(false),
                'Student Health' => self::featurePermissions(false),
                'PTM' => self::featurePermissions(false),
                'TC & Exit' => self::featurePermissions(false),
                'Messages' => self::featurePermissions(true),
                'Profile' => self::featurePermissions(true, false, true),
                'Edit Profile' => self::featurePermissions(true, false, true),
                'My Leaves' => self::featurePermissions(true, true, true),
            ],
        ];
    }

    private static function featurePermissions(bool $view, bool $add = false, bool $edit = false, bool $delete = false): array
    {
        return [
            'view' => $view,
            'add' => $add,
            'edit' => $edit,
            'delete' => $delete,
        ];
    }
}
